### ISSUE TITLE
MySQL server has gone away: SHOW FULL FIELDS FROM `builds`

### ISSUE THREAD

**Issue by kot-begemot** [gitlabhq/gitlab-ci#101]
We are continuously keep getting this error on out CI server. After some restarts (if there was a tine delay between stop and start), those errors is persistent, otherwise it would appear with ration of about 1:1.

    Worker
        SERVER:1879 on runner at about a minute ago 
    Class
        Runner
    Arguments
        84
    Exception
        ActiveRecord::StatementInvalid
    Error
        Mysql2::Error: MySQL server has gone away: SHOW FULL FIELDS FROM `builds`

    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in `execute_and_free'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:426:in `columns'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/model_schema.rb:228:in `yield'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/model_schema.rb:228:in `default'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/model_schema.rb:228:in `columns'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/model_schema.rb:237:in `columns_hash'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/delegation.rb:7:in `columns_hash'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/finder_methods.rb:331:in `find_one'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/finder_methods.rb:312:in `find_with_ids'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/relation/finder_methods.rb:107:in `find'
    /home/gitlab_ci/gitlab-ci/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/querying.rb:5:in `find'
    /home/gitlab_ci/gitlab-ci/lib/runner.rb:11:in `perform'

If you need any other information, please ask.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
