### ISSUE TITLE
Support for Environment Variables

### ISSUE THREAD

**Issue by NemesisRE** [gitlabhq/gitlab-ci#105]
Like Jenkins:
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

Gilab-CI is Perfect but my scripts need a variable for at least the git branch

**Comment by sammcj** [comment]
+1 I'd like to export things like local mirrors / proxies for package managers, i.e:

```
npm_config_registry=http://apt.bla.com/npm
```

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
