### ISSUE TITLE
Run build error

### ISSUE THREAD

**Issue by castovoid** [gitlabhq/gitlab-ci#125]
I'm using **Gitlab CI** from **master** commit f6e6637. Everything was running fine and now, when I try to run a build, a get this error:

```
Completed 500 Internal Server Error in 600ms

NoMethodError (undefined method `>>' for "x":String):
  app/models/project.rb:116:in `last_commit'
  app/models/build.rb:79:in `commit'
  app/models/build.rb:63:in `ci_skip?'
  app/controllers/projects_controller.rb:66:in `run'
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
