### ISSUE TITLE
Styling / functionality issues on 'Background Jobs' section

### ISSUE THREAD

**Issue by Seidr** [gitlabhq/gitlab-ci#129]
Was having same issues as described in Issue #127. When I changed to the master branch (instead of 2.0) the CSS/JS for the main front-end loads fine, however I'm now getting style issues on the 'Background Jobs' section once logged in. Also, all of the links in 'Background Jobs' seem to be broken. Could be something to do with the move from 'resque' to 'sidekiq' in the v2.0.0 commit? See attached screen shots.

It might be worth mentioning, this instance is running on the same server as a gitlab instance - could that have something to do with it? Perhaps the installation doc needs to be updated to reflect the changes introduction v2.0.0/v2.1.0?

Love gitlab, would love to be able to plug in gitlab ci also. Cheers

![gitlabci_background1](https://f.cloud.github.com/assets/795518/269640/d40559a6-8fa3-11e2-85a6-24b61fa523a6.png)
![gitlabci_background2](https://f.cloud.github.com/assets/795518/269641/d408746a-8fa3-11e2-8ed1-db62218019c6.png)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
