### ISSUE TITLE
Error when running build using ruby 2.0.0

### ISSUE THREAD

**Issue by michelsalib** [gitlabhq/gitlab-ci#130]
I just did a fresh install of gitlab_ci, I set up my project, and when clicking on run, I got a 500 with a message in my `production.log`:
```
Completed 500 Internal Server Error in 776ms

Grit::GitRuby::Internal::PackFormatError (pack /home/gitlab_ci/projects/computationbundle/.git/objects/pack/pack-f620acafec9561a33b1b7a7915c09$
  app/models/project.rb:116:in `last_commit'
  app/models/build.rb:79:in `commit'
  app/models/build.rb:63:in `ci_skip?'
  app/controllers/projects_controller.rb:67:in `run'
```

I dug up a little and discovered that running unser ruby 1.9.3 fixed the issue:
```
sudo su gitlab_ci
rvm install 1.9.3
rvm use 1.9.3 --default
exit
sudo service gitlab_ci restart
```

I seemed like a Grit issue, but just to be sure, I wanted to log the issue if someone run into the same problem.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
