### ISSUE TITLE
[Suggestion] Clockwork instead of Whenever

### ISSUE THREAD

**Issue by kirantpatil** [gitlabhq/gitlab-ci#164]
I read about Clockwork at http://adam.heroku.com/past/2010/6/30/replace_cron_with_clockwork/ and it is used by https://github.com/discourse/discourse.

Clockwork at https://github.com/tomykaira/clockwork.git.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
