### ISSUE TITLE
pass parameter to shell

### ISSUE THREAD

**Issue by liaohuangen** [gitlabhq/gitlab-ci#166]
Different people connect to gitlabci ,someone build one project. in this case, I want to reject the other one to build any other project.so If some parameters pass to shell such as username,email,compiling project's name,and so on it can be solved.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
