### ISSUE TITLE
Gitlab CI not starting without any errors

### ISSUE THREAD

**Issue by pietbrauer** [gitlabhq/gitlab-ci#179]
Hey,

I followed your setup tutorial for the third time now (after deleting the user each time) and I got the start script running without an error for the first time.

    Puma 2.0.0.b7 starting...
    * Min threads: 0, max threads: 16
    * Environment: production
    * Listening on unix:///home/gitlab_ci/gitlab-ci/tmp/sockets/gitlab-ci.socket
    Gitlab CI service started

In Nginx error log I see the following output:

    2013/05/21 19:13:30 [error] 4087#0: *1 connect() to unix:///home/gitlab_ci/gitlab-ci/tmp/sockets/gitlab-ci.socket failed (111: Connection refused) while connecting to upstream, client: 109.104.44.43, server: www.mydomain.com, request: "GET / HTTP/1.1", upstream: "http://unix:///home/gitlab_ci/gitlab-ci/tmp/sockets/gitlab-ci.socket:/", host: "mydomain.com"

And in browser I just get a `Nginx: 502 bad gateway`.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
