### ISSUE TITLE
Startup Guides

### ISSUE THREAD

**Issue by Weltraumente** [gitlabhq/gitlab-ci#180]
Hi Guys,

do not hit me please, but are there any startup guides or tutorials, where a newbie in ci can see a view example projects or some thing like that?

kind regards

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
