### ISSUE TITLE
error on service startup un ubuntu

### ISSUE THREAD

**Issue by mcgivrer** [gitlabhq/gitlab-ci#181]
After trying to install gitlab_ci, following your installation guide, i run into this error :

```bash
frederic@gitserver:~$ sudo service gitlab_ci start
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb:214:in `block in replace_gem': puma is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from /usr/local/bin/puma:22:in `<main>'
Gitlab CI service started
```

And as you can see, Gitlab CI is supposed to be executed. but it does not run ...

a simple sudo service gitlab_ci restart told me :

```bash
frederic@gitserver:~$ sudo service gitlab_ci restart
Error, GitLab CI not running!
``` 

Any idea about the install issue for the **stable-2.2**

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
