### ISSUE TITLE
Everybody see everyone's projects

### ISSUE THREAD

**Issue by JohnDup** [gitlabhq/gitlab-ci#210]
I can see everyone's Gitlab CI projects without rights on Gitlab.
Everyone can change parameters for every CI projects without granted.

**Comment by kainino0x** [comment]
I'm trying to use GitLab CI as a build/test system for student submissions in a University class. It seems that this means I either need to use another CI system or manually write a script to (somehow) email all of the build information to the student.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
