### ISSUE TITLE
Kill processes when cancel a build

### ISSUE THREAD

**Issue by neubi4** [gitlabhq/gitlab-ci#211]
When we cancel a build, the runner is running the test until the actual command ends.
Is it possible to kill the command on cancel?

When you only have on runner, is it annoying to wait until the canceled build is done to run a new build.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by nh2** [comment]
OK, I did that, everyone interested please upvote http://feedback.gitlab.com/forums/176466-general/suggestions/7156942-kill-processes-when-cancelling-a-build.

**Comment by ayufan** [comment]
@nh2 Isn't it already done?

**Comment by nh2** [comment]
@ayufan Is it?

**Comment by ayufan** [comment]
Yes, the process is killed if build got canceled.

**Comment by folki** [comment]
It doesn't seem to me this has been fixed.

Here is a simple test case. Please, create a project with the following content of the `.gitlab-ci.yml` file:
```yml
run_tests:
  stage: test
  script:
    - yes > /dev/null
```

If you cancel the build, the "yes" process is still running.

**Comment by folki** [comment]
Now I see, there's opened a separate issue for this: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1363
