### ISSUE TITLE
Upgrade docs need to talk about application.yml

### ISSUE THREAD

**Issue by tecnobrat** [gitlabhq/gitlab-ci#212]
The 2.X => 3.0 upgrade wiki doesn't explain that you need to copy config/application.yml.example to config/application.yml and edit it to include your gitlab URLs.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
