### ISSUE TITLE
When runners are removed from Gitlab-CI, delete their keys from the projects

### ISSUE THREAD

**Issue by weisjohn** [gitlabhq/gitlab-ci#218]
When I delete a runner from Gitlab-CI, it appears that their deploy keys are getting left behind. Over time, I'm afraid that this will clog up our install.

Thoughts?

**Comment by jvanbaarsen** [comment]
I agree with @davidolrik . I dont think this will cause your installation to clog up. If it is really giving you trouble please open a new issue with the exact problems you're facing.
