### ISSUE TITLE
Add project migration to upgrade docs

### ISSUE THREAD

**Issue by yakky** [gitlabhq/gitlab-ci#220]
In https://github.com/gitlabhq/gitlab-ci/wiki/Migrate-from-2.2-to-3.0 an upgrade path for existing projects should be mentioned::

GitLab project id (numeric id from the database) and ssh url to repository are requestd in the settings page to be able to add a runner to a project

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
