### ISSUE TITLE
Error 500, after migrate from version 2.2 to 3

### ISSUE THREAD

**Issue by gotlium** [gitlabhq/gitlab-ci#221]
After migration, I can't work with GC, because I'm getting page with 500 code.
Where I can see the logs?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
