### ISSUE TITLE
Do not see project from Gitlab without namespace

### ISSUE THREAD

**Issue by gotva** [gitlabhq/gitlab-ci#224]
Given a project in Gitlab without namespace. When an owner of the project goes to gitlab-ci-server/projects/gitlab he does not see it and can not add the project to CI.

I tried to find out where is the problem and it seems to me that the problem in Gitlab API. CI server displays "owned_projects" for current user from API https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/projects.rb#L30

In Gitlab `current_user.owned_projects` returns projects only with namespace
```ruby
u.owned_projects
  Project Load (0.6ms)  SELECT `projects`.* FROM `projects` INNER JOIN `namespaces` ON `projects`.`namespace_id` = `namespaces`.`id` WHERE `namespaces`.`owner_id` = 5
```
How can I add a project without namespace to Gitlab CI?

PS maybe this issue has smth common with this https://github.com/gitlabhq/gitlab-ci/pull/208

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
