### ISSUE TITLE
how to get the build-status and build-commiter 

### ISSUE THREAD

**Issue by yinxiaomei** [gitlabhq/gitlab-ci#225]
i installed the gitlab-ci 3.0. after run the project build, it will show us a list the build info. But what i want is that how    to get the build-status and build-commiter info by gitlab-ci api or someway else,the reason is that i want to use those above info in the build script.
PS: Recently i do not know how to send email to the project commiter or the owner when the build is failed.

**Comment by jvanbaarsen** [comment]
@yinxiaomei In the current version of GitLab CI Webhooks are present.
