### ISSUE TITLE
Show pusher at run overview

### ISSUE THREAD

**Issue by Mikulas** [gitlabhq/gitlab-ci#230]
The table of all pushes (ie http://ci.clevis.org/projects/1) could contain a name (email or whatever) of the pusher.

Our use case: we generally push feature commits from one developer at a time. That means the pusher is almost every time also the author of all those commits. It would be easier to immediately whose push failed and who is then responsible for fixing it. Right now it involves copying the hash and searching repo for the commits author.

Issue: pusher might not be author of all or any pushed commits, but in that case he shouldn't have pushed unknown untested code and should be responsible for the fail anyway.

**Now:**
![screenshot from 2013-07-19 11 14 08](https://f.cloud.github.com/assets/192200/824843/d3703d4c-f053-11e2-86a8-35bf90a3dc4a.png)

**Proposed:**
![screenshot from 2013-07-19 11 15 01](https://f.cloud.github.com/assets/192200/824844/d38a444e-f053-11e2-853d-f6e94c271b1b.png)

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
