### ISSUE TITLE
The build process remain stalled

### ISSUE THREAD

**Issue by CollateralStudios** [gitlabhq/gitlab-ci#237]
After several attempts, the build process via shell script not ever be completed.

http://www.youtube.com/watch?v=91MtMY-4ZcQ&hd=1

Linux Debian 7 64bit
GitLab CI 3.0.0 8484d33

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
