### ISSUE TITLE
Can I start build on all runners in same time?

### ISSUE THREAD

**Issue by BorMor** [gitlabhq/gitlab-ci#240]
Hi, I have gitlab 5.4 and gitlab-ci 3.0, how I can start build on all runners in same time?
Now only first runner make builds.

I'm use gitlab-ci for build c++ project on Windows and MacOS.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
