### ISSUE TITLE
.htaccess gets ignored on build

### ISSUE THREAD

**Issue by jakubriedl** [gitlabhq/gitlab-ci#245]
When I start build of php app it goes well but there is not .htaccess file in root. I can see the file in repository. It is there when I pull the branch, but in ci it is missing. .htaccess files in subdirectories remains so I think that there is probably some *.* file mask which the .htaccess file doesn't fit.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
