### ISSUE TITLE
Secure status badges with token

### ISSUE THREAD

**Issue by Mikulas** [gitlabhq/gitlab-ci#253]
Status badges are available publicly without login even though their corresponding project might be private. That is definitely just a minor issue, but in order to prevent guessing the url, it seems safer to add a validation against a token unique based on CI installation, project id and ref.

```diff
- http://example.com/projects/1/status.png?ref=master
+ http://example.com/projects/1/status.png?ref=master&token=6as5d4f
```

Without the token it is (to some extent, with enumeration) possible to list branches on a a private project (and get their CI status of course). It also helps that the `Content-Disposition` header returns the status as well, so the urls can be iterated over rather quickly.

Applies to all revisions (current master is a8a277fffafb8c37dd1c022d2dcfecd7123578b6 and older).

**Comment by jvanbaarsen** [comment]
If you like you can go ahead and create a PR for this.
