### ISSUE TITLE
Commit message shows description along with title

### ISSUE THREAD

**Issue by Mikulas** [gitlabhq/gitlab-ci#262]
Commit message should probably only render the commit title, not the whole description.

Example commit:
```
commit 3106188d64c8c1ea25fe67efb2ed9612e9f2090e
Author: Mikulas <rullaf@gmail.com>
Date:   Mon Aug 19 12:34:26 2013 +0200

    Clickthru: zobrazuje nl2br

    Samotna komponenta zatim neumoznuje newlines vkladat.
    Newlines muzou ale prijit treba z textarey.
```

**Expected** commit message: `Clickthru: zobrazuje nl2br`
**Rendered** commit message: `Clickthru: zobrazuje nl2br Samotna komponenta ...`

![screen shot 2013-08-19 at 12 38 17 pm](https://f.cloud.github.com/assets/192200/985395/933a890a-08bb-11e3-9198-52078c8f63aa.png)

**Comment by jvanbaarsen** [comment]
The "description" is part of the commit message. We show the entire commit message. This is behaviour that is designed to work this way
