### ISSUE TITLE
problem running gitlab and gitlab CI on same server

### ISSUE THREAD

**Issue by opichon** [gitlabhq/gitlab-ci#278]
I'm trying to run gitlab (6-0 stable) and gitlab CI (3-1 stable) on the same server (ubuntu/nginx). But the web page for CI always shows the Gitlab dashboard. (depending on how I start nginx, sometimes gitlab CI works, but gitlab shows the CI page).
service gitlab_ci status shows:
Gitlab CI service / Unicorn with PID 4584 is running.
Gitlab CI service / Sidekiq with PID 4606 is running.

This seems strange: I thought gitlab CI was using puma, not unicorn.

My install has followed the docs for the 3-1-stable branch.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
