### ISSUE TITLE
Allow Scripts to be based on the OS / Platform

### ISSUE THREAD

**Issue by neico** [gitlabhq/gitlab-ci#281]
Making this possible would allow to have a ci-runner on windows in the future, you just tell the CI project that you want to run something on a linux based runner, so only a runner that it on windows will execute that.

If the project has bother linux and windows runners then it'll use both.
This probably requires some rewriting of the CI internals as it would be necessary to have status badges for the different OS / Platform.

I'm also trying to make the runner work on windows currently, I'll make a pull request about that soon, but it would help if this would've been done before that...

  [1]: http://railsinstaller.org/        "RailsInstaller"

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
