### ISSUE TITLE
Changing Gitlab URL to project and ssh url to repository from the settings page doesn't update when a runner runs

### ISSUE THREAD

**Issue by felixpp** [gitlabhq/gitlab-ci#286]
Since I'm setupping a GitLab server for a project, with GitLabCi on a VM,  I often work from different networks, which gives this VM different IP addresses.

Turns out that my runners always checks out my project from the same IP Address I set up the CI project with at first, even though this address doesn't exist anymore, and even though I changed it in CI project's settings page : "GitLab URL to project" and "ssh url to repository".

When the runner runs its script, it gives a git error, which is totally normal, since the IP address is not the one I updated ssh url to.

------

ssh: connect to host first.ip.address.used port 22: Connection timed out
fatal: Could not read from remote repository.

------

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
