### ISSUE TITLE
Cannot save project / no project details

### ISSUE THREAD

**Issue by ryanberry** [gitlabhq/gitlab-ci#291]
Having issues adding projects from my Gitlab instance, I can't see any of the project details and when I add them I get a Cannot save project error.

The logs show the project details in the parameters:

Started POST "/projects" for  at 2013-10-03 15:53:39 +0800
Processing by ProjectsController#create as HTML
  Parameters: {******}
Redirected to http://myciserver/
Completed 302 Found in 14ms (ActiveRecord: 1.0ms)

![screen shot 2013-10-03 at 12 32 24 pm](https://f.cloud.github.com/assets/966324/1259955/f739b7c8-2bfc-11e3-89e2-7070792ebafa.jpg)

Both servers are Ubuntu 13.04

**Comment by clintberry** [comment]
I have gitlab and gitlab-ci installed on different servers, and configured it as such. It grabs the list from gitlab just fine, but when I click the add button next to a project, it says "Cannot Save Project". I am tailing all logs from gitlab-ctl and there are no errors anywhere. How can I diagnose this problem?
Gitlab version: 7.7.2
Gitlab-ci version: 5.4.2

**Comment by brauliobo** [comment]
@clintberry same here, using gitlab.com and own gitlab ci install
https://gitlab.com/help
http://gitlabci.eita.org.br/help

**Comment by ayufan** [comment]
Do you have master permission for the project?

On Sunday, February 15, 2015, Bráulio Bhavamitra <notifications@github.com>
wrote:

> @clintberry <https://github.com/clintberry> same here, using gitlab.com
> and own gitlab ci install
> https://gitlab.com/help
> http://gitlabci.eita.org.br/help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlab-ci/issues/291#issuecomment-74401061>.
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by brauliobo** [comment]
@ayufan Yeah, the gitlab-ci I installed lists the projects I own on gitlab.com.

**Comment by planrich** [comment]
The same is true for my installation. (Omnibus Gitlab 7.7.2,  GitLab CI 5.4.2). I tracked it down to app/models/network.rb
the call to:
  PUT http://example.com/api/v3/projects/34/services/gitlab-ci.json?private_token=abcdef
gitlab rails log says:
  Started GET "/api/v3/projects/48/services/gitlab-ci.json?private_token=abcdef" for 127.0.0.1 at 2015-02-18 20:40:56 +0100

I logged the error code: 405 Method not allowed.

**Comment by clintberry** [comment]
@planrich Did you have to change your nginx config?

**Comment by planrich** [comment]
For now I just patched the method and replaced 'http' with 'https'. I think I will regenerate my certificate, trust it locally on the machine and enter the https url on the gitlab ci config instead.

**Comment by brauliobo** [comment]
@planrich I'm not using https on gitlab-ci, but gitlab uses https. How can I do it then?

**Comment by brauliobo** [comment]
My mistake! Used

    gitlab_ci['gitlab_server'] = { "url" => 'http://gitlab.com',

Instead of 

    gitlab_ci['gitlab_server'] = { "url" => 'https://gitlab.com',

**Comment by brauliobo** [comment]
Now I don't know how to became an admin in my own gitlab-ci, as my user was created using 'Login with gitlab'

**Comment by brauliobo** [comment]
Sorry again, don't seem to be necessary, could setup runners

**Comment by Razer6** [comment]
This happens if you use https for GitLab CI but use a http URL for the application configuration within GitLab omniauth settings.
