### ISSUE TITLE
Unintentional destruction of build trace output via API call

### ISSUE THREAD

**Issue by alakra** [gitlabhq/gitlab-ci#295]
While looking through the API code, I noticed that this line could be unintentional destructive:

https://github.com/gitlabhq/gitlab-ci/blob/master/lib/api/builds.rb#L36

If the user only sets the `state` and not the `trace`, the `Build#update_attributes` call will set the `trace` to `nil` when it saves it, thus losing any previous trace data.

Also, the documentation for this particular API call is in error and has been fixed in https://github.com/gitlabhq/gitlab-ci/pull/293

**Comment by jvanbaarsen** [comment]
@alakra Thanks for the issue report. Ive prepared a fix.
