### ISSUE TITLE
Request body of API-Request is limited in size

### ISSUE THREAD

**Issue by Delphinator** [gitlabhq/gitlab-ci#305]
I'm currently working on an alternative runner implementation using python and docker. During testing I experienced `403 Forbidden` errors when the request body exceeded ~128k. This is easily reached while updating a build with a large trace. Steps to reproduce:

1. Get a runner token.

    ```
    RUNNER_TOKEN="..."
    ```

2. Grab a build

    ````
    curl -X POST -H "Content-Type: application/json" -d "{\"token\": \"$RUNNER_TOKEN\"}" http://localhost:1234/gitlab-ci/api/v1/builds/register.json
    {"id":812,"commands":"ls -la\r\npwd","ref":"master","sha":"...","project_id":2,"repo_url":"...","before_sha":"..."}
    ````    
    I got build 812, you number will vary.

3. PUT a valid update (optional, just an example how it should work)

    ````
    curl -X PUT -H "Content-Type: application/json" -d "{\"token\": \"$RUNNER_TOKEN\", \"state\": \"running\", \"trace\": \"foobar\n\"}" http://localhost:1234/gitlab-ci/api/v1/builds/812.json
    ````

4. PUT a big update

    ````
    echo -n "{\"token\": \"$RUNNER_TOKEN\", \"state\": \"running\", \"trace\": \"" > long_request
    for i in {1..20000}; do echo -n "aaaaaaaaaa" >> long_request; done
    echo -n "\n\"}" >> long_request
    curl -X PUT -H "Expect:" -H "Content-Type: application/json" -d @long_request http://localhost:1234/gitlab-ci/api/v1/builds/812.json
    {"message":"403 Forbidden"}
    ````
    
    The Expect header suppresses a `Expect: 100-continue` header that rails / rack cannot handle.

I did a bit of debugging and found that in [lib/api/helper.rb line 17](https://github.com/gitlabhq/gitlab-ci/blob/master/lib/api/helpers.rb#L17) `params` seems to be empty, therefore it cannot load the current runner and fails. I have no clue why the request body is not deserialized.

That's all I found out so far, and would really appreciate ideas and help finding a solution other than shorter traces.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
