### ISSUE TITLE
db:setup rake task fails

### ISSUE THREAD

**Issue by joshfriend** [gitlabhq/gitlab-ci#309]
I successfully installed GitLab yesterday, but ran into trouble with Gitlab CI today. Everything went smoothly until the Rake task to set up the databases.

Any help would be greatly appreciated.

Below is info about the system version, ruby version, etc and the traceback from the Rake failure:

    $ bundle --version
    Bundler version 1.3.5
    $ gem --version
    2.0.3
    $ ruby --version
    ruby 2.0.0p247 (2013-06-27 revision 41674) [i686-linux]
    $ uname -a
    Linux Whiplash 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:12:00 UTC 2013 i686 i686 i686 GNU/Linux
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 13.10
    Release:    13.10
    Codename:   saucy
    $ sudo -u gitlab_ci -H bundle exec rake db:setup  --trace RAILS_ENV=production
    gitlab_ci_production already exists
    rake aborted!
    (<unknown>): did not find expected '-' indicator while parsing a block collection at line 3 column 5
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
    /home/gitlab_ci/gitlab-ci/config/initializers/1_settings.rb:10:in `<top (required)>'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `block in load'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:592:in `each'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:592:in `block in <class:Engine>'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `instance_exec'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `run'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:55:in `block in run_initializers'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `each'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `run_initializers'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:136:in `initialize!'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /home/gitlab_ci/gitlab-ci/config/environment.rb:5:in `<top (required)>'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/backports-3.3.1/lib/backports/tools.rb:328:in `require'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/backports-3.3.1/lib/backports/tools.rb:328:in `require_with_backports'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in require'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:103:in `require_environment!'
    /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
    Tasks: TOP => db:setup => db:schema:load_if_ruby => environment

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
