### ISSUE TITLE
Failed adding runner deploy key to GitLab project

### ISSUE THREAD

**Issue by davidolrik** [gitlabhq/gitlab-ci#315]
I have registered a runner on my laptop, but I am unable to add this runner to any project as my id_rsa.pub is already in use in on my account in Gitlab.

When I try to add the runner to a project I get this error:

    Failed adding runner deploy key to GitLab project

Expected behaviour would be for Gitlab-ci to silently skip the key if it already exists.

Gitlab version 6.2.3 b490fde
Gitlab-ci version 3.2.0 e0c0609

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
