### ISSUE TITLE
Undocumented allow_git_fetch setting

### ISSUE THREAD

**Issue by samrocketman** [gitlabhq/gitlab-ci#316]
For project build settings there is an undocumented option `allow_git_fetch` for the gitlab-ci-runner.  This setting affects [clearing the project directory](https://github.com/gitlabhq/gitlab-ci-runner/blob/master/lib/build.rb#L32-L38) on the runner.  The runner gets this [setting from gitlab-ci projects](https://github.com/gitlabhq/gitlab-ci-runner/blob/master/lib/network.rb#L39).

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by samrocketman** [comment]
You make it sound like the issue was opened yesterday :-)

Not that I'm against closing it.  I don't use any of these feature so I leave it up to you to make imrovements.
