### ISSUE TITLE
Build edit page showing 500 error

### ISSUE THREAD

**Issue by mallikarjunece** [gitlabhq/gitlab-ci#322]
Hi ,
Just now I updated to gitlab ci 4.0.0.

I am getting 500 error on project edit page..
refer screenshot....

![screenshot from 2013-11-25 12 19 38](https://f.cloud.github.com/assets/1826210/1611040/d00565a6-559d-11e3-92d2-1b6b0d970be4.png)

Please let me know....

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
