### ISSUE TITLE
Assigning a worker breaks the enable/disable button layout

### ISSUE THREAD

**Issue by tuminoid** [gitlabhq/gitlab-ci#331]
Running CI 4.0.0.

Assigning a worker to a specific projects breaks the enable/disable button layout.

![screenshot](https://f.cloud.github.com/assets/853790/1661390/bdc94e78-5bdf-11e3-8c58-c9240761afed.png)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
