### ISSUE TITLE
gitlab-ci merge request

### ISSUE THREAD

**Issue by fzerorubigd** [gitlabhq/gitlab-ci#342]
I have gitlab and gitlab-ci installed in a machine in two user. every thing is fine but in merge request I get 
"Cannot connect to CI server. Please check your setting"

I have a repository called "base" and another repo (forked from "base") called "fork"

"base" is project 1 in gitlab-ci and "fork" is project 2

I have a commit with hash "fork_hash" in "fork", and I create a merge request to "base" 
The funny thing is the gitlab, request gitlab-ci to report hash "fork_hash" from project "base" (which is not there! its in project "fork" not "base") so the result is null : 
```
/projects/1/builds/fork_hash/status.json?token=project_token
```
result is null
This link from gitlab-ci is correct : 
```
/projects/2/builds/fork_hash/status.json?token=project_token
```
and the result is some thing like this : 
```
{"id":723,"sha":"d7d7ca1b5aec6c52953401a90063645d316fea08","status":"success"}
```

-- GitLab 6.3.1 779b4dc
-- GitLab CI 4.0.0 03f79de
-- Linux debian.mydomain.net 3.2.0-4-amd64 # 1 SMP Debian 3.2.46-1+deb7u1 x86_64 GNU/Linux

Installed via the official documentation.

First, I think its a gitlab issue :  https://github.com/gitlabhq/gitlabhq/issues/5855 but its not :)

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
