### ISSUE TITLE
Unexpected Rollback on insert new Projekt into Database

### ISSUE THREAD

**Issue by tomtone** [gitlabhq/gitlab-ci#344]
i can read out all projects from gitlab server instance, but on adding a projekt to build, the database rolls back after insert with following log entrys;

(0.2ms)  BEGIN
  Project Exists (0.4ms)  SELECT 1 AS one FROM `projects` WHERE `projects`.`name` = BINARY 'Namespace / project' LIMIT 1
  SQL (0.5ms)  INSERT INTO `projects` (`allow_git_fetch`, `always_build`, `created_at`, `default_ref`, `gitlab_id`, `gitlab_url`, `name`, `polling_interval`, `public`, `scripts`, `ssh_url_to_repo`, `timeout`, `token`, `updated_at`) VALUES (1, 0, '2013-12-18 14:07:46', 'master', 18, 'http://gitlab.url.de/namespace/project', 'Namespace  / project', NULL, 0, 'ls -la', 'git@gitlab.url.de:namespace/project.git', 1800, 'f409267c4f444ee97186daae7d8b15', '2013-12-18 14:07:46')
   (1.8ms)  ROLLBACK

The Projekt defenitly exists, User Permissions on database are set as described in installation.md and a manual insert will affect successfully. Any Ideas?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
