### ISSUE TITLE
GItlab-ci 4.1.0 LDAP not working

### ISSUE THREAD

**Issue by gbmtw** [gitlabhq/gitlab-ci#360]
We use:
gitlab version 6.2.0 
and
gitlab ci version 4.1.0

LDAP logins work fine directly on gitlab, but when an LDAP user tries to login via gitlab-ci we get "Invalid credentials" even through the user can login to gitlab with no problem.

Is there anything specifically relating to ldap that needs setting up on gitlab-ci?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
