### ISSUE TITLE
Latest build gives Error 500 when creating tag from UI

### ISSUE THREAD

**Issue by keith9820** [gitlabhq/gitlab-ci#370]
**GitLab 6.6.0.pre 98fe8fb**

When using the GitLab UI to create a new tag "v2.0.2" from "HEAD", I get a 500 error, but the tag is nevertheless created.  The error happens in Event.create_ref_event.  

The problem seems to be with commit 8587e3a357add7371b2286f3ab642c9ea8f58e2e

````
Parameters: {"project_id"=>"influencer-marketing/outlook-addin", "id"=>"v2.0.2a"}
Completed 500 Internal Server Error in 619ms
NoMethodError (undefined method `commit' for #<Gitlab::Git::Tag:0x00000004a40c78>):
app/models/event.rb:63:in `create_ref_event'
app/controllers/projects/tags_controller.rb:28:in `destroy'
app/controllers/application_controller.rb:57:in `set_current_user_for_thread' 
````

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
