### ISSUE TITLE
Use git archive instead of clone

### ISSUE THREAD

**Issue by txomon** [gitlabhq/gitlab-ci#371]
This is in theory a quite straightforward change, but providing git archive for getting faster a revision to test (instead of using git clone) would be a nice, cheap and fantastic feature.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
