### ISSUE TITLE
'Authentication failed' when pushing from CI back to Gitlab

### ISSUE THREAD

**Issue by acheloos-m** [gitlabhq/gitlab-ci#373]
**1. summary**

I'm using Gitlab-CI in combination with Capistrano and *cap-deploy-tagger* gem.
While pushing via Capistrano runs nice, i'm not able to push back a tag to my Gitlab Repository (for example 'deployed_to_staging'). There is no error in the gem so i tried to tag and push from Gitlab-Ci by Hand which leads to the following error:

`fatal: Authentication failed for 'http://gitlab-ci-token:MYPRIVATETOKEN@gitlaburl/user/capi_test.git/`

Somehow, the tags **are** stored *inside ci*, so you can't run the command in 2) twice, that will throw a 'tag exists' error. Also you can list the tags set by ci *inside ci* via `git tag`. Problem is, they won't show up in Gitlab. Also if i run the `git tag` command directly on the gitlab repo on my server from CLI it won't show tags.

*By the way: Cloning from Gitlab and all other regular tasks work without any errors*

**2. steps to reproduce**

Simply enter the following as your buildscript:
`git tag -a v1.4 -m 'version 1.4' && git push -f --tags`

**3. expected behavior**

A smooth push of the deployed tag which is then visible in GitLab

**4. related logs**

See 1). Also there are no relevant log entries in Gitlab.

Also I've already tried to not just provide a deploy-key to my GitLab project but also add a 'ci-server' user to my project, which *should* give the CI the rights to modify the GitLab repository -  but no luck there either.

**Comment by gadgetmg** [comment]
It seems the gitlab-ci-token only allows for pulling not pushing. @jsdir, how were you able to get a push working? Are you just doing a git push in your build script? Or are you somehow changing the way CI authenticates to GitLab?

**Comment by jsdir** [comment]
@gadgetmg I forget. I might have just pushed in the build script.

**Comment by mhamrah** [comment]
I had this problem, and it was simply because the name I was using in git did not have access to the repo I was pushing too.

**Comment by jvanbaarsen** [comment]
@acheloos-m Can you try @mhamrah solution? If it's not working please report back and I'll re-open this issue.

**Comment by acheloos-m** [comment]
@jvanbaarsen I forgot about this issue, sry. @mhamrah Solution seems to work. I'll try that later in detail.

**Comment by jvanbaarsen** [comment]
@acheloos-m Ok :)

**Comment by mhamrah** [comment]
Actually, my answer is incorrect, and I deleted it. The issue is that gitlab ci doesn't allow you to push with the gitlab-ci-token, only pull.In order to push, you do need a user with push permission set in your runner or your build script, You also need to reset the push url so the remote doesn't use the gitlab-ci-token user, but your user with push permissions:

git remote set-url --push origin https://<YOUR GIT USER NAME>@$GITLAB_SERVER_FQDN/<THE GIT PROJECT PATH>.git

There may be a better way.
