### ISSUE TITLE
generate new RUNNERS_TOKEN once used (optional?)

### ISSUE THREAD

**Issue by jokeyrhyme** [gitlabhq/gitlab-ci#378]
In order to make it more difficult for rogue gitlab-ci-runners to register, it might be more appropriate to only use each RUNNERS_TOKEN once, generating a brand new one.

@benbarclay and @danzy may also find this discussion interesting...

Thanks for the great work so far!

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.

**Comment by sammcj** [comment]
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1727
