### ISSUE TITLE
default to connecting to GitLab via HTTPS or SSH

### ISSUE THREAD

**Issue by jokeyrhyme** [gitlabhq/gitlab-ci#379]
It would be terrific if GitLab CI instructed Runners to connect to GitLab via HTTPS by default. Otherwise, the read-only token to access the repository is transmitted in plain text.

Alternatively, it might be better to configure the Runners to connect to GitLab via SSH, so that the deploy keys registered against the project are used.

@danzy and @benbarclay may be interested in this discussion...

Thanks so much for the great work so far!

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
