### ISSUE TITLE
Charts should not include data from cancelled builds

### ISSUE THREAD

**Issue by tuminoid** [gitlabhq/gitlab-ci#382]
Currently in charts all builds are included, also cancelled ones. For example, if CI runner gets stuck or crashes, and build job is cancelled much later, we get this kind of charts for the next full month: a big spike, flattening and making useless all other data points:
![Spike, flattening all other datapoints](https://f.cloud.github.com/assets/853790/2205104/7e8d8d1c-9949-11e3-8159-5d51d7e8f97a.PNG)

Same happens when you cancel a long build before it has taken much time, it creates a "pit" in the graph, again flattening all other data points.

Cancelled builds also cause crashes in Charts, such as #374.

**Comment by jvanbaarsen** [comment]
I think the problem is more in the fact that you have that many builds that are hanging. I think cancelled builds should be in the stats.
