### ISSUE TITLE
Add HipChat Integration

### ISSUE THREAD

**Issue by codyolsen** [gitlabhq/gitlab-ci#386]
Add hipchat notifications: With options for failed builds, or both completed and failed builds.

------------------

This is the configuration page in gitlab:
![screen shot 2014-02-26 at 4 06 03 pm](https://f.cloud.github.com/assets/3844315/2277030/b09d84aa-9f3a-11e3-85b6-4c1c34ff61c2.png)

**Comment by geshan** [comment]
how do I see the gitlab hipchat integration page?

**Comment by ayufan** [comment]
There is no HipChat service. You can add on top of my Service migration: https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/14 backported GitLab HipChat service.

**Comment by geshan** [comment]
It was easy I could do it on a repo level as an admin.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the feature request forum for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
