### ISSUE TITLE
AutoScroll not working

### ISSUE THREAD

**Issue by Freyskeyd** [gitlabhq/gitlab-ci#399]
Hey,

I'm trying to use autoscroll button, but nothing working. I don't get any update on the black board.

I'm on a debian64 wheezy, gitlab_ci 4.3, latest gitlab_runner.

**Comment by hannesa2** [comment]
I've the same issue.  Running and use direct url on ngnix it works, but when I use redirect with apache and a virtual host, it doesn't work. 
I only see this 
![autoscroll](https://cloud.githubusercontent.com/assets/3314607/18608806/c36b7d3c-7cf3-11e6-8e54-8f544ba6a0c0.png)
