### ISSUE TITLE
Unnecessary builds in multi-runner environment

### ISSUE THREAD

**Issue by n-e-g** [gitlabhq/gitlab-ci#458]
Happens in GitLab CI 5.0.1 ac0c1aa (I assume later as well)

The problem is, when you have may runners, e.g. 10 runners (in fact, these were gitlab_ci_runner), 
and you submit a commit to execute, it often happens that couple of runners start wotking on the same build (e.g. runner 1 and 2 will be building exactly the same, in parallel)

**Comment by vsizov** [comment]
fixed https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/82
Thank you all!
