### ISSUE TITLE
gitlab_ci init script: sudo require tty but it's not available at boot [AWS]

### ISSUE THREAD

**Issue by emilianobonassi** [gitlabhq/gitlab-ci#476]
I had some problems with gitlab_ci init script when it run on an CentOS (Amazon AMI).
In particular, the script doesn't start succesfully because at the boot yty aren't available and the default setting of sudo is to require it .

So, I inspected the script and I saw the lines responsible of  the problem, these are:
```
if [ "$USER" != "$app_user" ]; then
  sudo -u "$app_user" -H -i $0 "$@"; exit;
fi
```
I also have installed gitlab and it doesn't have any issue to start at boot time, so I inspected its init script , it does the same thing but using su. This is the code:

```
if [ "$USER" != "$app_user" ]; then
  eval su - "$app_user" -c $(echo \")$0 "$@"$(echo \"); exit;
fi
```

I'd two choices, disable requiretty in /etc/sudoers or substitute the part in the gitlab_ci script with the gitlab one. I chose the second one.

What do you think about that?

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by emilianobonassi** [comment]
I'm not experiencing the issue any more with the last version (GitLab CI 7.8.1 424cb42). Thank for have the issue closed.
