### ISSUE TITLE
Disable Gitlab Ci logs

### ISSUE THREAD

**Issue by gau1991** [gitlabhq/gitlab-ci#477]
Hi,
We are getting production.log around daily 150GB, 
```bash
^_^[root@easyengine.com:/home/gitlab_ci/gitlab-ci/log]# du -csh *
142G	production.log
```
On our server, one runner is running with gitlab-ci
We searched on wiki, found that, by default info log are by deafault enabled. 
```bash
  # See everything in the log (default is :info)
  # config.log_level = :debug
```

We request you to add option to disable log.

**Comment by jvanbaarsen** [comment]
@gau1991 I advice to use a log rotation system and if that is not sufficient change the log level in `config/environments/production.rb` to either `:fatal` or `:error`
