### ISSUE TITLE
Pretty Print the output from a command

### ISSUE THREAD

**Issue by suchitpuri** [gitlabhq/gitlab-ci#479]
In the gitlab ci i have a command which returns the output with new line \r\n in it . The console view in the build page does not interprets that and print \r\n instead of a new line. 
Is there a way to pretty print the output

**Comment by jvanbaarsen** [comment]
@suchitpuri Do you have an example of such output? I can't seem to reproduce this.

**Comment by vsizov** [comment]
closed due to lack of answer
