### ISSUE TITLE
backports 3.3.5 broken on ruby 2.1.3 (stable)

### ISSUE THREAD

**Issue by GenPage** [gitlabhq/gitlab-ci#480]
502 bad gateway when trying to access gitlab-ci

Backports 3.3.5 is broken in ruby stable (2.1.3) and fixed in their latest version 3.6.0

marcandre/backports#86

unicorn.stderr.log:
```
[2014-09-25T16:34:34.968377 #27334]  INFO -- : Refreshing Gem list
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb:2:in `close': Bad file descriptor @ fptr_finalize - /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/backports-3.3.5/lib/backports/1.9.1/io/open.rb (Errno::EBADF)
```

**Comment by jvanbaarsen** [comment]
This issue has been resolved.

**Comment by ohadpartuck** [comment]
10x,`bundle update backports` worked for me too

**Comment by shideneyu** [comment]
same, `bundle update backports` did the trick for me too.
