### ISSUE TITLE
Build page output sometimes shows old build output briefly

### ISSUE THREAD

**Issue by Burstaholic** [gitlabhq/gitlab-ci#481]
Occasionally, the entire text of the build output window will switch out with the output from an older, failed build. When this happens, both outputs usually alternate for the entire build time.

This seems be related to build failures, as I never see it with a successful build. In this case, I mean builds that fail due to reasons unrelated to the code being tested (git checkout failed, npm install failed, multiple runners fighting over the same build directory, etc.).

**Comment by jvanbaarsen** [comment]
Thanks for the issue report. Please reformat your issue to conform to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by vsizov** [comment]
closed due to lack of response
