### ISSUE TITLE
Black list projects for a runner

### ISSUE THREAD

**Issue by ericbulloch** [gitlabhq/gitlab-ci#491]
I really like the white list feature that is in gitlab ci for runners. I have a set up right now that includes many projects that are being worked on by different developers at different times.

It will be really nice to also have a black list projects feature for the runners. That way if one of our developers wants to change the build process for a project it will not affect everyone.

This will add a little bit of logic because you have to check if the runner is using the white list or the black list. Also I believe the white list and the black list are mutually exclusive, you don't want to have both for a runner.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
