### ISSUE TITLE
Build API Request Returns 400/CSRF Authenticity Error

### ISSUE THREAD

**Issue by paulbeattie** [gitlabhq/gitlab-ci#500]
Since upgrading to 5-2-stable when GitLab sends a build request to Gitlab CI the request is not processed due to a CSRF token authenticity error. The same happens if the POST request is sent manually. This worked for the first build after a clean setup of Gitlab CI and passed using the default build script. Subsequent requests are dropped.

Result from GitLab request
```
Processing by ProjectsController#build as HTML
  Parameters: {snipped}
Can't verify CSRF token authenticity
Completed 400 Bad Request in 6ms (ActiveRecord: 1.5ms)
```

cURL example
```
curl -X POST --data "token=snipped&ref=master" http://gitci.example.com/projects/1/build
```

cURL result
```
Processing by ProjectsController#build as */*
  Parameters: {"token"=>"snipped", "ref"=>"master", "id"=>"1"}
Can't verify CSRF token authenticity
```

**Comment by jvanbaarsen** [comment]
@paulbeattie This is a protection in the underlaying framework we use. A CSRF token needs to be present in order to prevent XSS. You should be using the API for manual posting.
