### ISSUE TITLE
"Add committer to recipients list" not working

### ISSUE THREAD

**Issue by TiagoCardoso1983** [gitlabhq/gitlab-ci#506]
We set this option by a certain project. By a merge request, it contains commits from several people. When merging it into the followed branch, when the build fails, I expect the email to be sent to all the committers responsible for the merge changes. Instead the email is being sent to the person that accepted the merge request (it seems that the "committer" is this person). This behaviour is strange and far beyond what I expected the feature to accomplish, since the "committer" is usually the technical product owner, who has his email already in the project recipients.

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
