### ISSUE TITLE
Inconsistency:  admin/projects vs. projects

### ISSUE THREAD

**Issue by vanboom** [gitlabhq/gitlab-ci#515]
Suggestion:  get rid of the admin/projects page.  

The interface is a bit inconsistent, depending on whether you get the project list from the Projects menu or the Gitlab CI Dashboard.

Seems the information provided on admin/project can be put on a panel in the normal project/show view. 

Thoughts?  

Thanks for such a great product!

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
