### ISSUE TITLE
GitlabCI retry build doesn't update new build settings

### ISSUE THREAD

**Issue by trongdong** [gitlabhq/gitlab-ci#516]
I searched and not sure if this is an issue or this is how Gitlab CI work. 
After updating a new build settings (adding new command) then click retry build, it will not update the new settings. 
I have to commit and push to make it run new build settings. 
What do you think?

**Comment by vsizov** [comment]
We will fix it soon. Thank you and sorry for possible inconvenience

**Comment by nfantone** [comment]
+1.

This is very confusing. The `README.md` states:

> If the build fails then adjust the build script and press the 'Retry' button on the build page

And this is just _not_ true. In the meantime, you should, at least, warn about the open issue in the documentation.

**Comment by CMLL** [comment]
Confirmed that happens. +1 Hope to get a fix soon. Thanks.

**Comment by nfantone** [comment]
No longer happening after upgrading to GitlabCI 5.4.2 and Gitlab 7.7.2. Retry button works fine.

This should be closed.

**Comment by maxlazio** [comment]
thanks @nfantone

**Comment by nfantone** [comment]
No problem.
