### ISSUE TITLE
Gitlab-CI API documentation broken (endless loop)

### ISSUE THREAD

**Issue by sammcj** [gitlabhq/gitlab-ci#521]
To reproduce:

1) Browse to http://doc.gitlab.com
2) Select Gitlab-CI
3) Select API

And you're back to the same page as in Step 1.

Fix:

Selecting API on the Gitlab-CI documentation page should link to http://doc.gitlab.com/ci/api/README.html

**Comment by connyay** [comment]
Looks like fixed by 535dc5934a932181c2e7a7292b1a406941aabde8

**Comment by vsizov** [comment]
I fixed, thank you.
