### ISSUE TITLE
Gitlab-CI doesn't build when tags are pushed

### ISSUE THREAD

**Issue by sammcj** [gitlabhq/gitlab-ci#522]
Gitlab-CI only seems to build when the branch is pushed, not when tags are pushed.

This is required functionality for many development workflows.

**Comment by huglester** [comment]
Do you have trigger enabled for tags in the project?

Trigger:
x Builds commits 
x Build tags

?

**Comment by nfantone** [comment]
Same here. Triggers are enabled.

We are using GitLab 7.6.2 along Gitlab CI 5.4.0. Do we need newer versions for tag builds to work?

**Comment by nfantone** [comment]
No longer happening after upgrading to GitlabCI 5.4.2 and Gitlab 7.7.2. 

@sammcj, my guess is that your Gitlab version is older than 7.7.

**Comment by sammcj** [comment]
Confirmed that 7.7 fixes the issue, thanks.
