### ISSUE TITLE
Add Gitlab-CI API request to trigger new build from branch / tag

### ISSUE THREAD

**Issue by sammcj** [gitlabhq/gitlab-ci#523]
As per http://doc.gitlab.com/ci/api/projects.html there is no way to trigger a new build from a branch or tag using the gitlab-ci API, adding support for this would be useful for many reasons including:

* A possible fix for #522
* Triggering a build as part of another project's build (think upstream dependencies)

**Comment by vsizov** [comment]
can we close this one?

**Comment by sammcj** [comment]
@vsizov has it been implemented in yesterdays release of GL 7.7 and GLCI 5.4?

**Comment by randx** [comment]
GitLab build is triggered when you push new tag

**Comment by sammcj** [comment]
And a new branch?

**Comment by nfantone** [comment]
Is there anyway I can configure a specific job to run on a given set of branches? Say, running a deploy build **only** triggered by pushes to `master`.

I have [asked this question over at StackOverflow](http://stackoverflow.com/questions/28026682/how-do-i-execute-a-job-for-specific-branch-tag-on-gitlab-ci-5-4) but I hardly got an answer.
