### ISSUE TITLE
Developers aren't able to access the build page (Error 404)

### ISSUE THREAD

**Issue by zedtux** [gitlabhq/gitlab-ci#525]
I'm administrator of Gitlab in my company so I have access to everything in Gitlab and Gitlab-CI.

When someone with the role Developer is going to Gitlab-CI, he can see the list of builds but open a build result in a 404 error while I can access it.

In my opinion, Developer should be able to access the build result page.

**Comment by carlosbaraza** [comment]
+1

**Comment by ayufan** [comment]
Do you test it on latest master?

**Comment by zedtux** [comment]
Nope, we are running the version 5.4.0.rc1(ec45548). Our infrastructure team is taking care of the upgrades. We can't switch to the version from master.

Is it fixed on master ?

**Comment by ayufan** [comment]
Nope. Not yet.

**Comment by kjeremy** [comment]
:+1:

**Comment by randx** [comment]
Fixed by 1533f3404621bd088cbe78ac7e2a14edc9915691
