### ISSUE TITLE
Unable to view a lot of Builds

### ISSUE THREAD

**Issue by darinkes** [gitlabhq/gitlab-ci#527]
I have a lot of Build which show results in 500 Internal Server Error.

```
Started GET "/projects/3/commits/a7df09d6b7e1b352342610124f22a3439899f19e" for unknown at 2015-01-19 17:47:41 +0100
Processing by CommitsController#show as HTML
  Parameters: {"project_id"=>"3", "id"=>"a7df09d6b7e1b352342610124f22a3439899f19e"}
Started POST "//api/v1/builds/register.json" for 127.0.0.1 at 2015-01-19 17:47:41 +0100
  Rendered builds/_build.html.haml (2.8ms)
  Rendered commits/show.html.haml within layouts/application (9.9ms)
Completed 500 Internal Server Error in 15ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    17:         &middot;
    18:         #{build.short_sha}
    19:   %td
    20:     = build.job.name
    21:     - if build.tags.any?
    22:       .pull-right
    23:         - build.tag_list.each do |tag|
  app/views/builds/_build.html.haml:20:in `_app_views_builds__build_html_haml__804838889958400519_52140840'
  app/views/commits/show.html.haml:67:in `_app_views_commits_show_html_haml__3625624918629173440_51411780'
```

Version: GitLab CI 5.4.0.rc3 91358db

Some Build can be shown succesfully. Whats wrong with the broken ones?

**Comment by ayufan** [comment]
I guess that older jobs don't have name assigned. 

Try to change build.job.name to build.job_name

**Comment by darinkes** [comment]
That does actually work \o/
Thanks for your hint.

So.. i guess there is a migration missing?

**Comment by ayufan** [comment]
I guess that not. I think that @randx did that on purpose.

**Comment by darinkes** [comment]
Ok. I'm curious about the reason, for presenting a 500 page instead of the old data :)

**Comment by ayufan** [comment]
500 page is the application unhandled exception :)

**Comment by darinkes** [comment]
I know, but I mean why this should be on purpose as you said :)

**Comment by randx** [comment]
Should be fixed in 1533f3404621bd088cbe78ac7e2a14edc9915691

**Comment by randx** [comment]
It will be available next release or as part of possible patch release

**Comment by darinkes** [comment]
@randx Thank you!
