### ISSUE TITLE
Build steps on gitlab-ci, How to get difference type of trigger from gitlab

### ISSUE THREAD

**Issue by nattaphat** [gitlabhq/gitlab-ci#528]
My issue is

When I config webhook on gitlab server to 'push events' and 'merge request events',
How to detect which event that fired current build on gitlab-ci, Example when current build on gitlab-ci is 'push events' I just run script block in build script to pull on develop server and when current build on gitlab-ci is 'merge' event I will run script block to pull on production server.

How to ?

**Comment by jvanbaarsen** [comment]
@nattaphat I'm not sure if I understand your issue, expand your description a little?

**Comment by vsizov** [comment]
closed due to lack of response
