### ISSUE TITLE
Unable to login to CI

### ISSUE THREAD

**Issue by zmszaman** [gitlabhq/gitlab-ci#529]
Hello,

After upgrading gitlab and gitlab-ci to latest version I was forced to switch protocol from http to https - when I'm creating new OAuth application in gitlab the redirect url must be https. I use self signed certificates which work great with gitlab but when I try to login to gitlab-ci I'm redirected to gitlab where I need to click to "authorize" button. After that gitlab-ci shows 500 error and in logs i have the following line:

```
Faraday::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  app/controllers/user_sessions_controller.rb:18:in `callback'
```

Is there any configuration option which I can use to disable certificate verification?

**Comment by ayufan** [comment]
You can may look into that issue: https://gitlab.com/gitlab-org/gitlab-ci/issues/89

**Comment by zmszaman** [comment]
Thanks for help. Now it works.
