### ISSUE TITLE
How to set up gitlab-ci for multiple gitlab sites

### ISSUE THREAD

**Issue by thomwiggers** [gitlabhq/gitlab-ci#531]
Prior to 5.3 you could set up multiple gitlab sites in `applications.yml`. How do I do that with the OAuth authentication?

**Comment by ayufan** [comment]
It's not possible now. Look here for explanation: https://gitlab.com/gitlab-org/gitlab-ci/issues/88

**Comment by thomwiggers** [comment]
dang.

**Comment by ayufan** [comment]
Yeah. Live is hard :)
