### ISSUE TITLE
Getting gem not found when all are installed via bundler.

### ISSUE THREAD

**Issue by bweston92** [gitlabhq/gitlab-ci#532]
```
gitlab_ci@raspberrypi ~/gitlab-ci/config $ bundle exec rake setup RAILS_ENV=produ                                                    ction
(in /home/gitlab_ci/gitlab-ci)
rake aborted!
LoadError: cannot load such file -- ice_nine
```

Any ideas?

**Comment by vsizov** [comment]
please provide more information. What did you do before? What's the system? and so on

**Comment by bweston92** [comment]
Ice nine isn't in the Gemfile. I installed the Gem manually after unfreezing bundler and it worked fine.


Using Raspberry PI using Raspbian. (model B+)


—

**Comment by ShiroiKuma** [comment]
I'm having this exact same problem, on a Raspberry Pi too, what did you do exactly to "unfreezing bundler" and install manually?

**Comment by bweston92** [comment]
Remove/change some file inside the vendor folder I can't exactly remember what sorry.
