### ISSUE TITLE
Use shields.io for badges

### ISSUE THREAD

**Issue by pradyun** [gitlabhq/gitlab-ci#533]
Hi all!

It would be nice if Gitlab CI used [shields.io](http://shields.io) badges. The current badges are inconsistent with the other badges, even on this repositories' README.

PS: I don't know if this is the right place for posting this issue... But it is one none-the less

**Comment by Wachiwi** [comment]
The gitlab team doesn't use the gitlab issue tracker for feature requests. If you want to submit a feature request you can do that at https://feedback.gitlab.com/. 
If you have submitted it post a link to your feature request inside this issue so others can vote for it :smile:.

**Comment by dblessing** [comment]
Thanks @wachiwi. 

@pradyun Please do submit a feature request at feedback.gitlab.com. I think this sounds like a good request.

**Comment by pradyun** [comment]
Thanks @dblessing and @Wachiwi.

Here's the [link](https://feedback.gitlab.com/forums/176466-general/suggestions/7011199-use-shields-io-for-badges) to the feature-request.
