### ISSUE TITLE
Create Jobs with API

### ISSUE THREAD

**Issue by kittools** [gitlabhq/gitlab-ci#536]
Hi,
It would be great to register/modify Jobs of the CI project via API. Or is there already such feature?

Regards
Dmitry

**Comment by vsizov** [comment]
There is MR (https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/37) for this but it has been reverted. I hope author of this will fix everything and we will merge it. Thank you.

**Comment by jvanbaarsen** [comment]
@kittools Someone is already working on this at https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/39. I'll close this issue for now.
