### ISSUE TITLE
Runner registration token can't be set to static

### ISSUE THREAD

**Issue by orodbhen** [gitlabhq/gitlab-ci#537]
I've configured a systemd unit template to create GitLab runner container and link it to GitLab CI by running:

    systemctl start gitlab-runner@<ID>.service

The only problem is that the registration token  keeps changing, so the configuration for that unit often has to be changed before starting it. 

I installed GitLab using the omnibus rpm, and I looked in gitlab.rb and didn't see any way to set the token to be static. Is there a way to do this? Or can the token be retrieved programmatically?

**Comment by jvanbaarsen** [comment]
@orodbhen The token keeps changing every time a new runner is registered. There is currently no way to make the token determanistic.
