### ISSUE TITLE
Make job template and accessible from projects separately

### ISSUE THREAD

**Issue by huglester** [gitlabhq/gitlab-ci#541]
Hello,

It would be nice, If we could define jobs, name it for example: `PHP Standarts`. It would execute commands like:
```php
vendor/bin/parallel-lint --exclude vendor --exclude _ide_helper.php .
vendor/bin/phpcs --standard=PSR1
```

Later, I could attach this command to every new project (something similar to Tags), so inside the job, I write project specific commands, and attach jobs: `PHP Standards`, `Some other job template`.

It would be nice to have, because for example - when time passes, and you want to swap:
`vendor/bin/phpcs --standard=PSR1` to something, for example: `vendor/bin/phpcs --standard=PSR2` we would need to revisit every project.

Thanks

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
