### ISSUE TITLE
make projects JOBS dependent on status of previous job?

### ISSUE THREAD

**Issue by huglester** [gitlabhq/gitlab-ci#544]
Hello,

for example I have `Project-1`, and it have 2 jobs named: `Build & Test` and `Deploy to production`

Is there a way, to make `Deploy to production` to be executed only IF `Build & Test` returned success?

I know I can put all those 'jobs' into one job, and then the script will be stopped on error.
But I somehow feel more comfortable in separating different types of jobs.

Or maybe it is already doable? 

Thank you!

**Comment by jvanbaarsen** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
