### ISSUE TITLE
Same sha on different branches not generating build correctly

### ISSUE THREAD

**Issue by awiddersheim** [gitlabhq/gitlab-ci#546]
We have been using a model in gitlab and gitlab-ci where we have devel and master branches. Typically, the master branch is considered "stable" and is only updated when a release is being put together. Most commits end up in the devel branch.

When we merge from devel into master it is sometimes done so a fast-forward is performed which means devel and master have the same sha. This is where the problem comes in. It appears gitlab-ci will attribute the merge/commits made to master when doing a new release back to the devel branch because the sha's match. Thus when doing the build the proper ref name is not used.

Note that when doing tagged builds they seem to work a little bit better. They get the proper ref name during the build.

Previous verisions of gitlab-ci seemed to handle this without issue but after updating to gitlab-ci 5.4.x it no longer does.

My guess is the problem is in the following:

https://github.com/gitlabhq/gitlab-ci/blob/master/app/services/create_commit_service.rb#L22-L48

The commit is only looked up based on the sha (which can be the same across different branches) and then creates the build with that information. Tags seem to go through their own build process logic which is probably why they work a bit better. Ideally, commits would get looked up by both their sha and ref name.

1. **Summary:** See above.
2. **Steps to reproduce:** Create two branches in gitlab, devel and master for example for a project with gitlab-ci support. Make some test commits to devel and push to gitlab. Now, gitlab-ci should build for devel. Merge those commits into master using fast-forward. Ensure devel and master have the same sha. Push changes to master to gitlab. Now gitlab-ci will do the build but with devel as the ref name.
3. **Expected behavior:**  When committing to a different branch, even if the sha already exists as a commit in gitlab-ci, it should build from that branch and not any branches seen previously.
4. **Observed behavior**: The build will be done using the branch seen in the first commit matching the same sha.
5. **Relevant logs and/or screenshots:** None.
6. **Possible fixes**: https://github.com/gitlabhq/gitlab-ci/blob/master/app/services/create_commit_service.rb#L22-L48 Look up commits by both sha and ref name.

**Comment by nfantone** [comment]
+1. Same issue here.

**Comment by xdobro4** [comment]
:+1:

**Comment by vsizov** [comment]
@awiddersheim We will have descussion with @randx  about this problem. But I want to say that it is good practic to create merge commit all the time with --no-ff flag. That how GitLab does it. We always create Merge Request for merging branch in GitLab B.V. 
Some links about this practic
http://stackoverflow.com/questions/9069061/what-is-the-difference-between-git-merge-and-git-merge-no-ff

http://blog.jonathanoliver.com/my-new-best-friend-git-merge-no-ff/

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by awiddersheim** [comment]
@vsizov Thanks for looking into it. I agree, in most cases having a merge commit is a good thing and considered "best practice" by a lot of people.

However, the nice thing about Git, Gitlab and Gitlab-CI has been their ability to be flexible enough to allow us to create work flows that make sense in our scenarios.

**Comment by ayufan** [comment]
I agree. The pretty common workflow in Git is to use rebase instead of
merge. Some people don't like merges :)

Kamil


On Tue, Mar 3, 2015 at 1:29 PM, Andrew Widdersheim <notifications@github.com
> wrote:

> @vsizov <https://github.com/vsizov> Thanks for looking into it. I agree,
> in most cases having a merge commit is a good thing and considered "best
> practice" by a lot of people.
>
> However, the nice thing about Git, Gitlab and Gitlab-CI has been their
> ability to be flexible enough to allow us to create work flows that make
> sense in our scenarios.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlab-ci/issues/546#issuecomment-76936620>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by vsizov** [comment]
@ayufan  of course you can use rebase. I use it every day. I'm talking about allowing to do fast-forward merge.

**Comment by vsizov** [comment]
We scheduled the fix to the coming release

**Comment by awiddersheim** [comment]
@vsizov Great news! Much appreciated.

**Comment by ayufan** [comment]
@vsizov I can do it.

My idea is to store in `builds.ref` not only `name`, but full reference (`refs/heads/branch` or `refs/heads/tags`). Which later be used as REF_NAME. It will also resolve the issue with showing builds as tagged when they got created from branch.

**Comment by vsizov** [comment]
@ayufan Thanks but it is already done.

**Comment by ayufan** [comment]
Can you point me where it is?

**Comment by vsizov** [comment]
It is on the our internal GitLab instance yet. I added ref name to commit url and also I've made appropriate change to GitLab side so it will pass this ref name.

**Comment by ayufan** [comment]
You mean CI?

**Comment by vsizov** [comment]
I mean I did two MRs, for GitLab  and GitLab CI sides. Because GitLab's MR is referring to CI, so I had to change this links as well.

**Comment by ayufan** [comment]
Ok. Thanks. Did you had time to fix tags as well? There are at least two issues related to tags which I know.

**Comment by vsizov** [comment]
What issues do you mean?

**Comment by ayufan** [comment]
https://gitlab.com/gitlab-org/gitlab-ci/issues/86 https://gitlab.com/gitlab-org/gitlab-ci/issues/90

**Comment by vsizov** [comment]
BTW, your firast message is not about current bug. It can fix another issue but not this. This issue is about finding commit by both ref name and sha

**Comment by ayufan** [comment]
Ok

**Comment by vsizov** [comment]
No, I had no time to fix those issues yet.

**Comment by tmelvin** [comment]
Ran into this problem a couple days ago, glad you guys are already on it! Thanks!

**Comment by ayufan** [comment]
@vsizov when do you guys plan to push it to master?

**Comment by vsizov** [comment]
We don't know yet. Sorry. We are busy with more important tasks.

**Comment by vsizov** [comment]
@ayufan You asked me to update you about this fix - 3d7eb9d9151773e01c34cf53dfc91e6bfc2207b3
@awiddersheim Unfortunatelly it would be available in 7.10 only.

**Comment by awiddersheim** [comment]
@vsizov Thanks for the fix. Just so I'm clear I have to wait at least one more release before this will be included?

**Comment by vsizov** [comment]
yes, it is in master branch now. So you have to wait :(

**Comment by ayufan** [comment]
@vsizov Thanks - i'll prepare fixes for other issues we were discussing.
