### ISSUE TITLE
Error: could not load

### ISSUE THREAD

**Issue by brunobatista** [gitlabhq/gitlab-ci#548]
When try run `/usr/bin/gitlab-ci-rake` or `/usr/bin/gitlab-ci-rails` I get this error:

```bash
/usr/bin/gitlab-ci-rake error: could not load /opt/gitlab/etc/gitlab-ci/gitlab-ci-rc
You can generate it with:   sudo gitlab-ctl reconfigure
```

Any idea how solve it? Thanks.

**Comment by vsizov** [comment]
How did you install CI?

**Comment by brunobatista** [comment]
Solved the issue, thanks @vsizov :+1: 

I downloaded wrong OS (Debian) version of gitlab.
