### ISSUE TITLE
oauth uses http callback when https is configured

### ISSUE THREAD

**Issue by dbakken** [gitlabhq/gitlab-ci#549]
After upgrading to version 5.4 and configuring oauth2, users are unable to login to Gitlab CI. There appears to be a bug which redirects users to an http callback url even if Gitlab CI is configured for https.

Clicking "Login with Gitlab" in Gitlab CI sends me to the following url:

https://gitlab.economicmodeling.com/oauth/authorize?client_id=foo&redirect_uri=http%3A%2F%2Fci-test.economicmodeling.com%2Fuser_sessions%2Fcallback&response_type=code

which incorrectly specifies an http redirect_url. The page says "An error has occurred
The redirect uri included is not valid." The callback url configured in Gitlab oauth applications is: 
https://ci-test.economicmodeling.com/user_sessions/callback.

Viewing https://ci-test.economicmodeling.com/help/oauth2 displays the following which is incorrect (should be https instead of http):
```
In the GitLab admin area under OAuth applications create a new entry.
The redirect url should be http://ci-test.economicmodeling.com/user_sessions/callback
```

gitlab url: https://gitlab.economicmodeling.com/
gitlab ci url: https://ci-test.economicmodeling.com/

(gitlab) gitlab.yml:
```
production: &base
  gitlab:
    host: gitlab.economicmodeling.com
    port: 443
    https: true
```

(gitlab ci) application.yml:
```
defaults: &defaults
  gitlab_server:
    url: 'https://gitlab.economicmodeling.com/'
    app_id: 'foo'
    app_secret: 'bar'

  gitlab_ci:
    host: ci-test.economicmodeling.com
    port: 443
    https: true
```

Gitlab CI production.log:
```
Started GET "/user_sessions/auth" for 127.0.0.1 at 2015-02-12 13:00:30 -0800
Processing by UserSessionsController#auth as HTML
Redirected to https://gitlab.economicmodeling.com/oauth/authorize?client_id=foo&redirect_uri=http%3A%2F%2Fci-test.economicmodeling.com%2Fuser_sessions%2Fcallback&response_type=code
Completed 302 Found in 3ms (ActiveRecord: 0.6ms)
```

Gitlab production.log:
```
Started GET "/oauth/authorize?client_id=foo&redirect_uri=http%3A%2F%2Fci-test.economicmodeling.com%2Fuser_sessions%2Fcallback&response_type=code" for 127.0.0.1 at 2015-02-12 12:58:38 -0800
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"foo", "redirect_uri"=>"http://ci-test.economicmodeling.com/user_sessions/callback", "response_type"=>"code"}
```

Apache2 is configured as a reverse proxy for Gitlab which also redirects http to https:
```
<VirtualHost 64.126.168.200:80>
  ServerName gitlab.economicmodeling.com
  Redirect permanent / https://gitlab.economicmodeling.com/
</VirtualHost>
<VirtualHost 64.126.168.200:443>
  ServerName gitlab.economicmodeling.com
  DocumentRoot /home/git/gitlab/public

  ProxyRequests Off
  ProxyPreserveHost On
  ProxyPass /uploads !
  ProxyPass / http://127.0.0.1:9292/
  <Location />
  ProxyPassReverse /
      Order deny,allow
      Allow from all
  </Location>

  RewriteEngine on
  RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
  RewriteRule .* http://127.0.0.1:9292%{REQUEST_URI} [P,QSA]
  RequestHeader set X_FORWARDED_PROTO 'https'

  SSLEngine On
  SSLCertificateFile /path/to/crt
  SSLCertificateKeyFile /path/to/key
  SSLCertificateChainFile /path/to/chainfile
</VirtualHost>
```

With a similar setup for Gitlab CI:
```
<VirtualHost 64.126.168.200:80>
  ServerName ci-test.economicmodeling.com
  Redirect permanent / https://ci-test.economicmodeling.com/
</VirtualHost>
<VirtualHost 64.126.168.200:443>
  ServerName ci-test.economicmodeling.com
  DocumentRoot /home/gitlab_ci_test/gitlab-ci/public

  ProxyRequests Off
  ProxyPreserveHost On
  ProxyPass /uploads !
  ProxyPass / http://127.0.0.1:9494/
  <Location />
  ProxyPassReverse /
      Order deny,allow
      Allow from all
  </Location>

  SSLEngine On
  SSLCertificateFile /path/to/crt
  SSLCertificateKeyFile /path/to/key
  SSLCertificateChainFile /path/to/chainfile
</VirtualHost>
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by vsizov** [comment]
@dbakken Try to add 
```
RequestHeader set X-Forwarded-Proto "https"
```
to VirtualHost section of apache

**Comment by jvanbaarsen** [comment]
I'm sorry, I might have closed this issue a bit to hasty!

**Comment by dbakken** [comment]
Thank you, @vsizov! Adding X-Forwarded-Proto "https" to my Gitlab CI apache2 vhost fixed the redirect problem. An update to the Gitlab CI docs would make this clear to anyone using apache.
