### ISSUE TITLE
doc: provide a one shoot script for updating (and provided proposal)

### ISSUE THREAD

**Issue by jpahullo** [gitlabhq/gitlab-ci#560]
Hi all!

Comparing to gitlab, which we are provided with one-shoot script for updating from source, I found it here missing.

To do so, I built this script to do so. It works ok for me, in my installation:

```
sudo service gitlab_ci stop; \
cd /home/gitlab_ci/gitlab-ci; \
sudo -u gitlab_ci -H git pull origin `git rev-parse --abbrev-ref HEAD`; \
sudo -u gitlab_ci -H bundle install --without development test --deployment; \
sudo -u gitlab_ci -H bundle exec rake db:migrate RAILS_ENV=production; \
cd; \
sudo service gitlab_ci start
```

Since when we start this gitlab_ci service, the document `db/schema.rb` is shown always as modified for git, we could even do like this, if and only if, we are sure we only have that modification:

```
sudo service gitlab_ci stop; \
cd /home/gitlab_ci/gitlab-ci; \
sudo -u gitlab_ci -H git checkout -f `git rev-parse --abbrev-ref HEAD`; \
sudo -u gitlab_ci -H git pull origin `git rev-parse --abbrev-ref HEAD`; \
sudo -u gitlab_ci -H bundle install --without development test --deployment; \
sudo -u gitlab_ci -H bundle exec rake db:migrate RAILS_ENV=production; \
cd; \
sudo service gitlab_ci start
```

The `git checkout -f` forces to omit any existing local change.

If you want, you even could replace the `; \` for `&& \` so that the one line script stops if anything fails.

Hopings this helps!

**Comment by Wachiwi** [comment]
:+1:

**Comment by vsizov** [comment]
Where can I find it for GitLab?

**Comment by jpahullo** [comment]
At https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/upgrader.md at the bottom of the page. :smile:

**Comment by vsizov** [comment]
Could you make a PR?

**Comment by jpahullo** [comment]
done!

**Comment by Razer6** [comment]
Closing as PR is merged :)
