### ISSUE TITLE
Retry button is hidden for developers

### ISSUE THREAD

**Issue by GriGrim** [gitlabhq/gitlab-ci#563]
After upgrading to GitlabCI 5.4.2 and Gitlab 7.7.2 'Retry' button no longer appears on the build page when build fails.
I (as developer) cannot see it:
![no_retry](https://cloud.githubusercontent.com/assets/2479756/6688119/a1dd9a10-ccb9-11e4-81ae-17a107956b9c.png)
At the same time group owner can see it (rotating arrow on the right side):
![retry](https://cloud.githubusercontent.com/assets/2479756/6688170/f659ffc0-ccb9-11e4-854a-a5ba4117adaa.png)
Should there be some special settings set or it is a feature of new version?
How can I get 'Retry' button back?

**Comment by vsizov** [comment]
Retry button is hidden for builds which can not be retried. The new version of GitLabCI does not support old builds fully.

**Comment by GriGrim** [comment]
But why owner of the project can see it?

**Comment by vsizov** [comment]
I changed title.

**Comment by randx** [comment]
I think we should fix it. Otherwise I retry builds for developers which is painful process

**Comment by vsizov** [comment]
!52

**Comment by vsizov** [comment]
merged
