### ISSUE TITLE
"Cannot connect to the CI server" when all builds canceled

### ISSUE THREAD

**Issue by zedtux** [gitlabhq/gitlab-ci#564]
Today I had 3 merge requests, in my Gitlab 7.7.2 bd98290, where the following message is displayed:

> Cannot connect to the CI server. Please check your settings and try again.

while for 7 others, the message was correct (build success or failed).

I've found in Gitlab-CI the builds and saw that in the case I have the message, all builds were canceled. Using the "Retry" button "fixed" the issue as I can now see the message "CI build pending for XXXXXX".

So it seems that the message "Cannot connect to the CI server." is shown until at least one build is not in state "canceled".

**Comment by vsizov** [comment]
I can confirm this bug

**Comment by zedtux** [comment]
Thank you @vsizov and @randx ! :+1:

**Comment by vsizov** [comment]
It will be available in 7.9
