### ISSUE TITLE
Time in words vs. exact time.

### ISSUE THREAD

**Issue by carlosbaraza** [gitlabhq/gitlab-ci#565]
Hi,

In my team, we are using the CI for a build that takes "around 1 hour". However, we would like to have the exact time for all the timings displayed in the CI. We know that the build takes ages to complete, but it could be great to know how much exactly it takes in order to plan and optimise.

If such modification is developed, and all the times/durations are replaced by the exact times, would it be accepted in the the Gitlab CI repo? Another possibility is to leave this as a configurable option.

Thank you for this great tool,
Carlos.

**Comment by vsizov** [comment]
Good idea.

**Comment by vsizov** [comment]
https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/78
