### ISSUE TITLE
Coordinator doesn't supply branch name to runner

### ISSUE THREAD

**Issue by SPARTAN563** [gitlabhq/gitlab-ci#567]
### Summary
The `/api/v1/builds/register.json` method supplies information to the GitLab CI build runner including the current `@ref`, `@sha` and so on. In the case of standard commits, `@ref` is the name of the branch on which the commit was made, while in the case of tags it is the name of the tag. Unfortunately this makes it impossible to write a runner does not operate in a detached head state under all circumstances - breaking support for tools like GitVersion.

### Investigation
This issue was first notices as a result of using GitVersion. For those of you not familiar with what GitVersion does, it automatically generates predictable versioning information for a git repository based on your tags, branches and other factors. [More Information Here](https://github.com/ParticularLabs/GitVersion).

Part of this requires GitVersion to know which branch a commit was made on when building (for example, a feature/* branch would be treated differently to master when the same commit is built). I've addressed some of this in our Windows based test runner [Marathon](https://github.com/emssconsulting/marathon) however I have now hit a limitation in the information sent by GitLab CI when a tag is pushed - namely that the branch name is replaced with the name of the tag.

### Technical Details
The current runner will always fail as it checks out the `build_ref` directly by doing the following:

```bash
git reset --hard
git checkout $sha
```

It can be fixed to operate correctly by instead running the following (which is what Marathon does).

```bash
git checkout $ref
git reset --hard $sha
```
This resets the head of `$ref_name` to point to `$ref` rather than checking out `$ref` in a detached head state, allowing gitversion to work correctly.

I will open up an issue/pull request for this on the runner repository - this issue doesn't deal with that but rather with the need for some changes to the coordinator.

### Reproducing Failure
The failure case can be reproduced by quickly checking out a tag on any repository and then attempting to run GitVersion.

```bash
git clone https://github.com/emssconsulting/marathon.git
git checkout v1.2.8-beta # checkout a tag
gitversion # will fail due to the HEAD being in a detached state
git status # should show a warning about being in a detached head state
```

### Solving the Problem
The problem can be solved by doing the following instead within the runner.

```bash
git clone https://github.com/emssconsulting/marathon.git
git checkout master # checkout the master branch
git reset --hard v1.2.8-beta # checkout the tag on the current branch
git status # should show no changes on master branch (may be behind or ahead of origin/master)
gitversion # should show the correct output - FullSemVer: 1.2.8-beta 
```

So to quickly template it in Ruby - keeping in mind that `@branch_name != @ref_name`.

```ruby
cmd = []
cmd << "cd #{project_dir}"
cmd << "git checkout #{@branch_name}"
cmd << "git reset --hard #{@ref}"
cmd.join(" && ")
```

So, what needs to be changed on the GitLab CI side? We just need to supply the `@branch_name` to the runner when a build is requested through `/api/v1/builds/register.json`.

### Where changes need to be made
 - **GitLab CI Runner**
    - [Build Initialization](https://github.com/gitlabhq/gitlab-ci-runner/blob/master/lib/build.rb#L16)
    - [Build Checkout](https://github.com/gitlabhq/gitlab-ci-runner/blob/master/lib/build.rb#L157)

- **GitLab CI**
   - Requires investigation

If you need any further clarification on the issue, assistance with implementing the changes or for me to fix up anything in this issue please don't hesitate to let me know.

### Alternative Solutions
 - Use something like `git branch --contains <tag>` to determine the branch a tag belongs to (problem is that multiple branches can "contain" the same tag).
 - Use `git checkout -B $ref $sha` in the builder to always create a new branch with the specified `@ref` name (this is the temporary solution I have settled on for Marathon).

**Comment by ayufan** [comment]
Nice review. You may be interested in my https://github.com/ayufan/gitlab-ci-multi-runner which uses `git checkout -B`

**Comment by SPARTAN563** [comment]
That's the solution I've adopted in Marathon as a stopgap solution - however in my opinion it doesn't really solve the problem in a terribly nice way as it forces GitVersion to believe that the tag is in fact a branch.
There's also a couple of other reasons why we're using Marathon, namely built in support for PowerShell and global runner environment configuration steps (allows us to configure the environment on a per-runner basis without having to manipulate the GitLab CI instance job scripts - things like loading the `vsvars.bat` file so that tools like `msbuild` become available to our runners).

**Comment by ayufan** [comment]
@SPARTAN563 the main problem is that once you receive the tag you don't really know from what branch it is. Of course tag can be on one branch, but it's not uncommon to have it on multiple ones. 

GitVersion is nice (I haven't know about it). Right now for versioning I use: `git describe --tags` which handles most of cases :)

**Comment by SPARTAN563** [comment]
That's true, however by virtue of the way tags are handled it is necessary to push the commit to which a tag points either with or before the tag itself . This means that GitLab CI should always manage to resolve the branch (it manages when viewing the builds for a commit at [https://ci.example.com/projects/{project_id}/commits/{sha}](#).


Here's a quick screengrab from that page showing that it resolves the branch name correctly - even in cases where there are tags present.

![image](https://cloud.githubusercontent.com/assets/1760260/6822148/275ab29a-d2e6-11e4-880f-9252378911fd.png)

Now there's obviously the issue of which branch wins in cases where the same commit is pushed to multiple branches at the same time.

Here's a quick example which illustrates this issue (and could be used to determine which way this is handled in GitLab CI currently).
```bash
# Setup the branches
git checkout -B test1
git push --set-upstream origin test1
git checkout -B test 2
git push --set-upstream origin test2

# Generate the commit
git checkout test1
touch .test
git add .test
git commit -m "Branch win test"

# Make sure it's on test2 as well
git checkout test2
git merge test1

# Toss both branches up and hope for the best
git push --all origin
```

As for `git describe --tags`, very cool and definitely something I'll look at for some of the projects. Unfortunately there are use cases (especially where .NET is concerned) that GitVersion covers such as automatically versioning the compiled assembly - something which would require additional preprocessing on the output of `git describe --tags` to transform it into a usable form.

**Comment by ayufan** [comment]
> Here's a quick screengrab from that page showing that it resolves the branch name correctly - even in cases where there are tags present.

This behaviour is changed in upcoming release. Generally tag can also not be attached to any branch at all.

> Now there's obviously the issue of which branch wins in cases where the same commit is pushed to multiple branches at the same time.

I guess that this is unresolvable. I think that best is not to enforce it on coordinator side, but allow the script to detect whether the tag is on desired branch.

**Comment by SPARTAN563** [comment]
I see, that's unfortunate but I can't think of a better way to handle it either.

Also noticed that GitVersion seems to be happy dealing with detached heads when they are at the head of a branch - I'm going to fiddle with it some more and see whether there's a way to make it work when rebuilding an older tag (may require something like the following).

```bash
git checkout {tag}
git reset --hard {sha} # Reset the branch head to the current commit's SHA
git checkout {tag} # If it's a tag, this will checkout the tag again, if it's a branch it won't do anything
```

I'll let you know how that goes, if it works then it may be possible to resolve the issue on the runner side.

**Comment by ayufan** [comment]
I'm still not quite sure what you want to achieve :)

**Comment by SPARTAN563** [comment]
Trying to get GitVersion working without extra boilerplate code in the job scripts or the need for a custom runner (in an ideal world). For some reason it was failing when building a specific tag and after testing the process manually I managed to reproduce it with the steps outlined in the first post.

Of course, it couldn't possibly be that easy :stuck_out_tongue_closed_eyes: - attempting to reproduce it now is failing (i.e. everything works as one would expect it to).

What I'm doing at the moment on the runner side is running the commands below (with no modifications to the coordinator).

```bash
git clone {originUrl}
git checkout {ref}
git reset --hard {sha}
```

Given that the problem doesn't appear to be reliably reproducible and due to the uncertainty of how to approach solving the original issue - I'm going to settle on doing it this way and hoping it works from now on (i.e. not using `git checkout -B {ref} {sha}`). Combined with your comment that vNext will not group tags and commits together, and I think the only change that needs to happen is on the Runner side so that when working with branches and tags we don't checkout in a detached head state.

As soon as I get the chance, I'll make the requisite changes to the runner and open a pull request there for that part of the process - I'm sure there'll need to be an investigation into the ramifications of making that change with regards to backwards compatibility.
