### ISSUE TITLE
Incorrect CI_BUILD_REF_NAME when merging to master

### ISSUE THREAD

**Issue by mhamrah** [gitlabhq/gitlab-ci#569]
If I open a merge request in gitlab, and either:

- accept the merge request in gitlab
- merge the branch manually into master and push

The associated gitlab ci build does not see that as a change to the master branch, but the source branch that wanted to merge. This causes any build commands for the master branch in the build script to not run. The only workaround is to push a fresh commit to the master branch.

Is there an easy way or setting so a merge to master shows as a master branch change, not a branch change?

**Comment by vsizov** [comment]
Thank you for you report. This bug was fixed in master and will be available in 7.10 release.
related #546
