### ISSUE TITLE
Runners remain shared even when all projects are un-assigned

### ISSUE THREAD

**Issue by fgimian** [gitlabhq/gitlab-ci#571]
Hey there guys, this is an easy one to reproduce:

1. Create a Shared runner
2. Assign one project to it
3. Un-assign that project from it (so there are no projects assigned)
4. Noticed that it still remains a **Specific** runner instead of turning back into a shared runner?

It seems that the **is_shared** property isn't reverted correctly to **true**.

## Workaround ##

1. Jump into the database:

   ``` bash
   sudo -u gitlab-psql /opt/gitlab/embedded/bin/psql -d gitlab_ci_production
   ```

2. Find the id of the runner you wish to fix:

   ``` sql
   SELECT id, description, token, is_shared
   FROM runners;
   ```

3. Update the is_shared flag to switch it back to a shared runner:

   ``` sql
   UPDATE runners
   SET is_shared = true
   WHERE id = <id>;
   ```

I'm sadly not a Rails guru and even after looking at the code couldn't determine how to fix it.

Any help would be greatly appreciated! :smile: 
Fotis

**Comment by vsizov** [comment]
Thank you, I will look into it.

**Comment by fgimian** [comment]
Thank you so much! :smile:

**Comment by vsizov** [comment]
This transition is prohibited because of security reason. Private runners contain cached repository. So if you make private runner shared, someone can steal your code. We decided to allow only one way transition.

**Comment by vsizov** [comment]
Title and body of your issue are mismatched. This is why i was confused.

**Comment by tovine** [comment]
First of all I want to apologize for necroposting, but my comment is directly related to it so it feels better than opening a new issue.  
With that out of the way: would it not be possible to clear the cache of the runner so it can once again be made shared? It seems to me that it would just be a matter of clearing out some directories and removing any Docker containers, or am I missing something?
It's clearly less work than having to set up a new runner and remove the old one...
