### ISSUE TITLE
No button to edit project from /admin/projects/X

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlab-ci#572]
it's a bit frustating, to edit a project i can't simply click on 'projects' in the top bar and edit one 
i need to click on build, choose a  build, click on edit job and then i will see the menu to edit other properties of a job :/

**Comment by vsizov** [comment]
Here is button:

![joxi_screenshot_1427879532927](https://cloud.githubusercontent.com/assets/417636/6937975/703347fc-d868-11e4-8480-d47605b984ff.png)

**Comment by allan-simon** [comment]
Interesting i don't have it...
and i'm using latest version (7.9.1) 
![selection_008](https://cloud.githubusercontent.com/assets/213167/6938136/a2e701a4-d893-11e4-84df-a2d1fc6bbcbe.jpg)

**Comment by vsizov** [comment]
There is a check `current_user.can_manage_project?`. So can you manage that project?

**Comment by allan-simon** [comment]
normally i'm "admin" in gitlab so my guess was that i could edit any project 

let me check my "role" in that specific project

**Comment by andynu** [comment]
@vsizov, where were you looking? I don't see an attempt to display the link in 7-9-stable's [/app/views/admin/projects/show.html.haml](https://github.com/gitlabhq/gitlab-ci/blob/7-9-stable/app/views/admin/projects/show.html.haml).

**Comment by allan-simon** [comment]
@andynu thanks =)

**Comment by vsizov** [comment]
We reworked UI in 7.10 and I think this problem will not confuse you anymore. Feel free to reopen if this issue still exist for you.

**Comment by allan-simon** [comment]
no problem, thanks
