### ISSUE TITLE
Serious design flaw: can't have one runner to run all MRs

### ISSUE THREAD

**Issue by brauliobo** [gitlabhq/gitlab-ci#575]
The way gitlab CI is designed today, each fork has to setup its own runner so that the project can test merge requests (MRs). That makes completely inviable to test MRs, as setting up a runner is not trivial.

Are there any plans to support MRs runs from the target repository?

**Comment by vsizov** [comment]
We are working on it

**Comment by vsizov** [comment]
It is in master and will be available in 7.10

**Comment by brauliobo** [comment]
@vsizov great!

**Comment by brauliobo** [comment]
hello @vsizov. I see https://ci.gitlab.com was updated, but can't figure out how to use it. the closes thing to me is shared runners, but stills MRs do not associate to the main runner.

**Comment by vsizov** [comment]
7.10 has not been released yet. After release you have to create fork again.

**Comment by brauliobo** [comment]
@vsizov any news on this? i see ci.gitlab.com and gitlab.com already are using 7.10, but still I can't see how to do this. I've tried with a new fork also.

**Comment by vsizov** [comment]
Just created fork and MR - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/644.
Everything is OK.
You need to have shared runners and origin project should allow using shared runners.

**Comment by vsizov** [comment]
Anyway GitLabCI design will be changed soon.

**Comment by brauliobo** [comment]
@vsizov just tried forking a repo from a friend (enabled on gitlab-ci), commiting a change, creating an MR and haven't got any gitlab-ci message of the job in the MR.

@vsizov in the link you've sent, there isn't any link to gitlab-ci job. how could you see it worked?

**Comment by vsizov** [comment]
> just tried forking a repo from a friend (enabled on gitlab-ci), commiting a change, creating an MR and haven't got any gitlab-ci message of the job in the MR.

What do you mean with "message of the job"?

> in the link you've sent, there isn't any link to gitlab-ci job. how could you see it worked?

I created that MR 27 days ago. I hoped you have enough time to check it and removed fork 2 days ago. So You will not find anything now.

**Comment by vsizov** [comment]
Please send screenshots for all cases you are talking about.
