### ISSUE TITLE
No Link to Project Commits List from Build Page

### ISSUE THREAD

**Issue by andrewmunsell** [gitlabhq/gitlab-ci#577]
Right now, on the build page there's only a link to take you back to the build list for that commit. While this can be useful, most of the time the commit only has a single (successful) build, so it'd be quite useful to have a link that goes directly back to the list of commits. 

This page:

```
https://ci.gitlab.com/projects/[PROJECT]/builds/[BUILD]
```

Should have a link to this page:

```
https://ci.gitlab.com/projects/[PROJECT]
```

On the build details page and the build list, it would make sense to just hyperlink the project name at the top like the commit hash is on the build list page.

**Comment by vsizov** [comment]
good idea. I think we can make project name clickable.

**Comment by vsizov** [comment]
https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/76 done
