### ISSUE TITLE
Unable to build code and then run tests in parallel

### ISSUE THREAD

**Issue by artlepool** [gitlabhq/gitlab-ci#578]
Maybe I'm doing something wrong here, or my general approach just isn't fitting with the GitLab CI flow.

In order to run our integration tests for our product, you need to ensure bundler is installed and have run a "bundle install" to set up and install/update the gem dependencies.  

Once this has been done, then I'd like the integration tests to run. For example we could split our integration tests into 3 or 4 chunks and run these in parallel.

On GitLab CI, I can't see any way to only run one job for a project first (not in parallel), and then have all other parallel jobs start after its finished.  Is this something that GitLab CI can do?

I guess I'd like to understand how other people are using the GitLab CI. For example, to run our acceptance tests, we'd need to make sure there was a fully up-to-date deployment of our software that was accessible for the tests to run.  But if I can't use GitLab CI to deploy the software first, THEN run all the tests, how could I make this work?
We currently use TeamCity as our CI server, where you can set up a series of jobs in sequence which works well for us, but doesn't take advantage of parallel jobs as standard.

**Comment by vsizov** [comment]
GitLab CI is not designed for this because each build is independent. But it is OK to run `bundle install` for each build. 'bundle install` takes few seconds (if it is not first time run), so it is not a big overhead.

**Comment by artlepool** [comment]
Thanks @vsizov, appreciate your fast response.

Could you maybe give me an indication of how GitLab CI is designed to be used as I'm not 100% clear on this.  By design, does it assume that you already have a deployed system somewhere that is ready to be tested?   Or is GitLab CI only for running tests that don't require install or deployments?

**Comment by vsizov** [comment]
I'm working on documentation for jobs. But I can give you a quick example:

```
export PATH=~/bin:/usr/local/bin:/usr/bin:/bin
gem install bundler 
cp config/database.yml.mysql config/database.yml
cp config/application.yml.example config/application.yml
bundle
RAILS_ENV=test bundle exec rake db:setup 
RAILS_ENV=test bundle exec rake spec
```

**Comment by vsizov** [comment]
So you need to setup runner first to be able  to run tests

**Comment by vsizov** [comment]
I recommend you to try to run tests on runner manually. Maker sure that everything work as expected.

**Comment by vsizov** [comment]
https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/jobs Documentation

**Comment by artlepool** [comment]
Thanks @vsizov.

Yes I already have a build runner and I'm successfully running my tests. But I'm not sure how I can run them in parallel. If I was to split my tests up in to 3 chunks, how would I do all the setup stuff (eg. gem install bundler, bundle, rake db:setup, etc) once and then run the 3 chunks of tests in parallel?

How would you take the example you've given, and take advantage of parallel jobs/tests? Do you have an example where there are multiple jobs running in parallel?

**Comment by vsizov** [comment]
You have to have more than one runner. In this case if you have several parallel jobs then runners will execute them in parallel

**Comment by Razer6** [comment]
@artlepool You might want to try out [gitlab-ci-multi-runner(https://github.com/ayufan/gitlab-ci-multi-runner/tree/master) which allows to have concurrent jobs one one machine.

**Comment by artlepool** [comment]
Right, so if I have multiple runners, then it will do a git clone/fetch on each of the runners, run the setup setups, and then run the tests that you've assigned it to run?  I think I get it now.

I guess I was approaching this in a slightly different way the GitLab CI was designed but your explanations make it clear, thanks very much @vsizov!

And thanks @Razer6, will certainly check it out.
