### ISSUE TITLE
save changes for jobs 

### ISSUE THREAD

**Issue by madogao** [gitlabhq/gitlab-ci#580]
I  add a project to ci with a shared runner.
I want to add a test job.
I input the name then click the "Save changes" button.
I can see the message "Project was successfully updated!" bug nothing to be saved.
why?

**Comment by madogao** [comment]
This is the log in production.log:

Started PATCH "/projects/1" for 127.0.0.1 at 2015-04-16 14:28:50 +0800
Processing by ProjectsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"QFFf9RpB+cAR8lNtgb/E52KtUYYCtLxqMCihmoev3aY=", "project"=>{"jobs_attributes"=>{"0"=>{"name"=>"testjob", "build_branches"=>"1", "build_tags"=>"0", "tag_list"=>"", "commands"=>"git submodule update --init\r\nls -la\r\n", "_destroy"=>"false", "id"=>"1"}}}, "commit"=>"Save changes", "id"=>"1"}
Redirected to http://ci.cxtech360.com/projects/1
Completed 302 Found in 18ms (ActiveRecord: 3.9ms)
Started GET "/projects/1" for 127.0.0.1 at 2015-04-16 14:28:50 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"1"}
  Parameters: {"id"=>"1"}
  Rendered shared/_guide.html.haml (0.9ms)
  Rendered collection (0.0ms)
  Rendered projects/show.html.haml within layouts/project (7.3ms)
  Rendered layouts/_head.html.haml (1.2ms)
  Rendered layouts/_nav.html.haml (1.9ms)
  Rendered layouts/_info.html.haml (1.4ms)
  Rendered layouts/_nav_project.html.haml (4.9ms)
Completed 200 OK in 25ms (Views: 18.1ms | ActiveRecord: 2.1ms)
Started GET "/assets/application-36368ffd31562f8448f51aaebbf3b068.js" for 127.0.0.1 at 2015-04-16 14:28:50 +0800
Started GET "/assets/no_avatar-10360078ab706cf6989537f307a57c6e.png" for 127.0.0.1 at 2015-04-16 14:28:50 +0800
Started GET "/assets/fontawesome-webfont-4a09858bcb98f48530e46e8338eb16de.woff" for 127.0.0.1 at 2015-04-16 14:28:50 +0800

**Comment by vsizov** [comment]
version? How did you install it?

**Comment by madogao** [comment]
I install it from source  tomorrow
like this: git clone https://github.com/gitlabhq/gitlab-ci.git

**Comment by vsizov** [comment]
never use master branch, I fixed it yesterday.
