### ISSUE TITLE
Slack Service does not allow you to pick Channel / Username

### ISSUE THREAD

**Issue by giggsey** [gitlabhq/gitlab-ci#581]
In GitLab, the Slack Service integrations allow you to pick the Channel and Username used for Slack. GitLab CI does not offer this.

**Comment by paulinder** [comment]
Googling brought me here... @giggsey - did you end up getting Gitlab CI to integrate with Slack? When I press the 'Test Settings' button on Gitlab CI I get 'We tried to test the service but error occured'.

**Comment by giggsey** [comment]
We disabled it, as we didn't want it writing to the default channel.

In actual GitLab, I believe where the Slack settings are stored was
changed. Its possible the same was done for CI.

**Comment by ayufan2** [comment]
To have Slack notifications for specific channel (or private group or yourself) you have to create new integration and select channel for it.

**Comment by giggsey** [comment]
@ayufan Indeed, but I don't want to waste an integration just for GitLab CI.

The Slack integration in GitLab has the ability to set Channel and Username, so it makes sense that GitLab CI offers the same functionality.

**Comment by leejo** [comment]
@paulinder - did you get anywhere with the `We tried to test the service but error occured` message?

**Comment by paulinder** [comment]
Have you managed to run any test jobs at all yet? I'm not quite sure what fixed it, but I have noticed that pressing the `Test settings` button tries to send the last test passed/failed message. If no tests have been run (and no pass/fail message exists) I think GitlabCI has no message to use for a test.

**Comment by ayufan** [comment]
Thanks for the reports. I'll look into it.

**Comment by leejo** [comment]
Yes, this now works as we have test runs. As @paulinder says it seems to fail until there is a passed/failed message available.

**Comment by giggsey** [comment]
No longer an issue as GitLab CI is now built into GitLab, and it shares the same Slack settings.
