### ISSUE TITLE
Jobs don't honor Tags list.

### ISSUE THREAD

**Issue by robodude666** [gitlabhq/gitlab-ci#583]
I have two runners:

* Runner A with Tags: A
* Runner B with Tags: B

I've created two Jobs that both use tag B. The first Job starts on Runner B, however, the second starts immediately on Runner A. If I have only one job, then it'll always start on Runner A.

I'm using Gitlab CI 7.9.3.

**Comment by vsizov** [comment]
Can't reproduce on both branches 7.9.4 and master.

**Comment by vsizov** [comment]
Please add more information for reproducing that and open request again. Screenshots will be appreciated
