### ISSUE TITLE
shared runner not working

### ISSUE THREAD

**Issue by FireUponSky** [gitlabhq/gitlab-ci#584]
I upgrade my gitlab-ci to 7.9.4 today, but shared runner is not responding to any build action. However specific runner works fine. Another problem is disable all assignee projects fail to change the runner's type to shared.

**Comment by vsizov** [comment]
Please go to the project settings and find there option - "Allow shared runners".

**Comment by FireUponSky** [comment]
@vsizov Great, thanks for helping!

**Comment by lanchongyizu** [comment]
How to use shared runner on GitLab Enterprise Edition 8.2.0-ee?

**Comment by maxlazio** [comment]
@lanchongyizu Please contact support address you've received when you've purchased EE subscription to get help with your question.

**Comment by lanchongyizu** [comment]
@maxlazio I have not purchased EE, I just signed up on GitLab, maybe it is CE.
