### ISSUE TITLE
Status pending

### ISSUE THREAD

**Issue by kwdiwt** [gitlabhq/gitlab-ci#587]
gitlab-7.9.4_omnibus 
![qq photo20150425102345](https://cloud.githubusercontent.com/assets/7121840/7331108/865644d2-eb35-11e4-9fea-eed515460c91.jpg)
What is the method to check whether there is wrong with this

**Comment by vsizov** [comment]
I don't understand what the problem is? Your runner doesn't process job? or what?

**Comment by kwdiwt** [comment]
@vsizov 
Yes, My gitlab-7.9.1 may running, but I don't know why the gitlab-7.92 and gitlab-7.9.4 don't working, always show 'Status pending'

**Comment by ayufan** [comment]
Allow shared runners by default set to false :)



On Monday, April 27, 2015, ChenFeng <notifications@github.com> wrote:

> @vsizov <https://github.com/vsizov>
> Yes, My gitlab-7.9.1 may running, but I don't know why the gitlab-7.92 and
> gitlab-7.9.4 don't working, always show 'Status pending'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlab-ci/issues/587#issuecomment-96464364>.
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by kwdiwt** [comment]
very thankful

**Comment by ayufan** [comment]
I guess it would be nice to have it configurable with application.yml and
by default set to true :)

/cc @vsizov

**Comment by vsizov** [comment]
@ayufan No, we can't set it to true by default because shared runners are not safe.

**Comment by vsizov** [comment]
Make sense to me.
