### ISSUE TITLE
Duration time does not take into account parallelism of jobs

### ISSUE THREAD

**Issue by Heliosmaster** [gitlabhq/gitlab-ci#589]
Currently, the duration time of a commit is the sum of the time of the jobs, whereas it should be the longest of the (parallel) jobs that make it.

Assume you have two jobs, J1 (15 minutes) and J2 (10 minutes) that are run on a specific commit. Right now it displays a duration of 25 minutes, and I think the correct one is 15.

**Comment by vsizov** [comment]
We was thinking about it. But there are several questions: 
* What should we show when one of the builds started with long delay? For example in 2 hour.  
* What if build for longest job will fail? in this case durations will look like the line of random numbers. 

But sum of the time of the jobs has real physical value - it measures how long run your test suite in total.
