### ISSUE TITLE
Retry button is hidden for admins

### ISSUE THREAD

**Issue by dreis2211** [gitlabhq/gitlab-ci#595]
Hey,

after the update to the latest stable version 7.10 (we were on 5.0 before), we recognized that the retry button is missing. We quickly found the following links:
 - https://github.com/gitlabhq/gitlab-ci/issues/563
 - https://gitlab.com/gitlab-org/gitlab-ci/merge_requests/52/diffs

Although, we like the restrictions that were made for normal project members/developers - as an admin it is necessary to retry builds for projects once in a while you don't have access to.

Cheers

**Comment by vsizov** [comment]
Please install recent version. We don't accept issue for old versions.
