### ISSUE TITLE
[Request] Deploy jobs on tags

### ISSUE THREAD

**Issue by nfantone** [gitlabhq/gitlab-ci#603]
Recently, in our company, we have upgraded our **Gitlab CI** instance as we noticed that since `v7.9.0`, deploy jobs were implemented. And that was exactly what we were looking for.

What we actually needed was the ability to deploy artifacts to our Nexus repository, _after all tests ran successfully_. Artifacts are tightly linked to `git` tags. This is very typical: for every git, numbered tag, there's either a `war`, `jar` or `zip` bundled deployed artifact somewhere. So, we were using _tag push events_ and _build tags_ triggers in order to achieve that. But we lacked the _"after all tests ran"_ feature: we were just issuing a deploy on every pushed tag. 

To our surprise, having installed CI `7.11.4` version, we realized that the _deploy job_ pages did not have the same options as the regular job's. And there was no way of making a deploy job running **only on pushed tags**. So, now we are back to our old setup, with normal jobs and empty deploy tabs.

Perhaps, we had the wrong expectations, but it really made sense to us that, following basic OOP inheritance ideas, a _deploy job_ **would be** a _job_, extending what the latter already offered.

Having said all that, we asked if there is any way to achieve what we are looking for. And if there isn't, could this be a feasible feature to be put into consideration for GitlabCI?

**Comment by vsizov** [comment]
It will be available in coming 7.12 version. gitlab-ci.yml file contains all these options you needed.

**Comment by nfantone** [comment]
Great news! Thank you. Any potential release date?

**Comment by vsizov** [comment]
22 June as always :)
