### ISSUE TITLE
using docker inside gitlab-runner

### ISSUE THREAD

**Issue by fokoenecke** [gitlabhq/gitlab-ci#614]
I am trying to build a setup where my `gitlab-runner` is using docker for building and pushing an application image as described [here](http://doc.gitlab.com/ci/docker/using_docker_build.html) in option 2. Everything seems to work fine, till I get to the point, where the docker socket is called.

**.gitlab-ci.yml:**
``` yml
myjob:
  script:
  - docker --version #works fine
  - docker info #produces error
```

When the script tries to get docker info, I get following **error message**:
``` console
$ docker info
Get http:///var/run/docker.sock/v1.19/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

I am starting the runner by calling this **script**.
``` shell
#!/usr/bin/env bash
docker rm -f gitlab-runner
sudo docker run -d --name gitlab-runner --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /srv/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner:alpine
gitlab-runner register -n \
  --url http://ci.mysite.net/ \
  --registration-token $1 \
  --executor docker \
  --description "gitlab builder" \
  --docker-image "gitlab/dind:latest" \
  --docker-privileged
```
If I change the **executor** for `shell` (basically option 1 in the example), it is working. I slightly modified the `dind image` by copying a ceritficate in `Dockerfile`. 
``` Dockerfile
COPY assets/ca.crt /etc/ssl/certs/ca-certificates.crt
```
Any ideas where this could originate?

greetz!

**Comment by ayufan** [comment]
Do you run runner in docker image or on host system?

**Comment by ayufan** [comment]
Please also post the head lines of build log. There should be some information about dind image.

**Comment by fokoenecke** [comment]
I am using the runner in a docker image, although I had to install it on the host system to get it working.

``` console
gitlab-ci-multi-runner 0.5.0 (c38415a)
Using Docker executor with image gitlab-build:v1 ... 
Running on runner-51cfe3c8-project-2-concurrent-0 via mysite...

Cloning repository...
```

`gitlab-build:v1` is the modified `dind` image.

**Comment by fokoenecke** [comment]
Since I discovered some other strange behaviour in docker, I was looking for misconfigurations there. It turns out, that my linux kernel is older than the current requirement. I'll try to update it and let you know.
Thanks for your effort.

**Comment by ayufan** [comment]
Pretty strange problem. Everything should work ok. Feel free to open the issue if you have more questions.

**Comment by fokoenecke** [comment]
It seems to work now.
I updated my kernel first (from 3.2 to 3.16). That fixed the docker issues, but I still had problems running `docker info` inside my runner. Then I fixed the docker-runner setup by removing it from the host system and calling it properly inside my runner container:

``` shell
docker exec -it gitlab-runner gitlab-ci-multi-runner register \
  --non-interactive \
  --url http://ci.mysite.net/ \
  --registration-token $1 \
  --executor docker \
  --description "gitlab builder" \
  --docker-image "gitlab-build:v1" \
  --docker-privileged
```

Still the **same error** though. After that I changed the runner configuration inside my containers `/etc/gitlab-runner/config.toml` to 
``` console
[[runners]]
  name = "gitlab builder"
  url = "http://ci.mysite.net/"
  token = "aa9f9cce4940d105a5b51858185fa7"
  limit = 1
  executor = "docker"
  [runners.docker]
    image = "gitlab-build:v1"
    privileged = true
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock:rw"]
``` 
Basically adding docker.sock to the volumes by adding this `"/var/run/docker.sock:/var/run/docker.sock:rw"`.

Finally I get this result, when running the initial job:
``` console
gitlab-ci-multi-runner 0.5.0 (c38415a)
Using Docker executor with image gitlab-build:v1 ...
Running on runner-aa9f9cce-project-2-concurrent-0 via 31b8230da405...

Cloning repository...
Cloning into '/builds/okoenecke/day-break-frontend'...
Checking out de82973b as ci-config...

$ docker --version
Docker version 1.7.1, build 786b29d
$ docker info
Containers: 15
Images: 45
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
WARNING: No memory limit support
WARNING: No swap limit support
Total Memory: 31.35 GiB
Name: mysite
ID: G5WU:72SB:G5GJ:WNNW:PVWL:DO7X:7IKJ:YVCA:TASY:HNRS:RXS6:SZK7

Build succeeded.
```

Don't know if it working like intended now, but at least its working for me :)

**Comment by xiemeilong** [comment]
I have the same issue. Why "/var/run/docker.sock:/var/run/docker.sock:rw" not added by default?

**Comment by urquilla** [comment]
Had the same issue and as @fokoenecke said was worked it around adding "/var/run/docker.sock:/var/run/docker.sock:rw" to the config.toml

**Comment by Hubbitus** [comment]
Shouldn't be it at least mentioned in documentation??

**Comment by oozone** [comment]
Glad I stumbled on this, same issue here, added /var/run/docker.sock to volumes and the process ran, documentation is severely lacking in this regard.

**Comment by kmturley** [comment]
Seems like it might also be possible to pass through as a command:
`
gitlab-runner register --docker-privileged true --docker-volumes /var/run/docker.sock:/var/run/docker.sock`

**Comment by fokoenecke** [comment]
Just for the info:
This seems to be fixed without using a workaround now. Maybe it's because there is an official `docker:dind` image. But if you run that as a service like [described](https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor), it works fine for us.
