### ISSUE TITLE
API: 500 Server Error when assigning runner to ci project

### ISSUE THREAD

**Issue by michaKFromParis** [gitlabhq/gitlab-ci#618]
Hi,

I've been using the gitlab / gitlab ci api for a while now with great satisfaction through [NGitLab] (https://github.com/Scooletz/NGitLab) and [gitlab-ci.net] (https://github.com/michaKFromParis/gitlab-ci.net)

through the api I:
- create a project on gitlab
- create a project on gitlab ci associated to it
- enable gitlab ci service on the gitlab project
- lookup available runners
- assign first available runner to the ci project
- push the repo to gitlab

All of the above works perfectly except the runner assignation.
I tracked the urls and logs:

I get the list of available runners and get the id of the first one in the list
```
GET https://ci.gitlab.com/api/v1/runners?private_token=XXXXXXXXXXXX&url=https://gitlab.com
```
I assign the runner like this:

```
POST https://ci.gitlab.com/api/v1/projects/5952/runners/1173?private_token=XXXXXXXXXXXX&url=https://gitlab.com
with this post data "id=5952&runner_id=1173"
```

The output for the last API call is not even json:

```
{"message"=>"500 Internal Server Error"}
```

When I look at the production log, the top of the stack is:

```
Started GET "/api/v1/runners?private_token= XXXXXXXXXXXX&url=https://gitlab.example.com" for 127.0.0.1 at 2015-08-13 21:39:29 +0200
Started POST "/api/v1/projects/28/runners/1?private_token= XXXXXXXXXXXX&url=https://gitlab.example.com" for 127.0.0.1 at 2015-08-13 21:39:29 +0200

Network::UnauthorizedError (Network::UnauthorizedError):
  /home/gitlab_ci/gitlab-ci/app/models/network.rb:111:in `build_response'
  /home/gitlab_ci/gitlab-ci/app/models/network.rb:62:in `project_hooks'
  /home/gitlab_ci/gitlab-ci/app/models/user.rb:64:in `block in can_manage_project?'
  /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/cache.rb:296:in `block in fetch'
  /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/cache.rb:587:in `block in save_block_result_to_cache'
  /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/cache.rb:548:in `instrument'
  /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/cache.rb:586:in `save_block_result_to_cache'
  /home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/cache.rb:296:in `fetch'
  /home/gitlab_ci/gitlab-ci/app/models/user.rb:63:in `can_manage_project?'
  /home/gitlab_ci/gitlab-ci/lib/api/projects.rb:162:in `block (2 levels) in <class:Projects>'
```

the culprit line of code is:

```ruby
unauthorized! unless current_user.can_manage_project?(project.gitlab_id)
```

but it looks like querying can_manage_project makes the application crash

Thanks

**Comment by michaKFromParis** [comment]
Hi, Just bumping the issue. Any clue ? Any one ?

**Comment by ayufan** [comment]
There are API errors that are fixed in upcoming release. You will have option to grab and test it on RC tomorrow.

**Comment by michaKFromParis** [comment]
Great. Thanks for taking the time to reply

On Wednesday, August 19, 2015, Kamil Trzciński <notifications@github.com>
wrote:

> There are API errors that are fixed in upcoming release. You will have
> option to grab and test it on RC tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitlabhq/gitlab-ci/issues/618#issuecomment-132370660>.
>


-- 
Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by michaKFromParis** [comment]
I confirm it's fixed. Thanks!
