### ISSUE TITLE
gitlab-ci.yaml regexp not work

### ISSUE THREAD

**Issue by Matrix-Zhang** [gitlabhq/gitlab-ci#629]
the example :
job:
  only:
    - /^issue-.*$/ # use regexp

i commit a change, and the commit message is "issue-01"

but the gitlab-ci told me the build was skipped....

how to use regexp in only keyword? 

3ks

**Comment by Matrix-Zhang** [comment]
here is my .gitlab-ci.yaml

stages:
    - build
    - deploy

job_build:
    script: "./build_scripts/build.sh"
    stage: build
    only:
        - tags
        - /^issue-.*$/

**Comment by ayufan** [comment]
It works: the only and except filters are for ref names: branches and tags, not commit message.
