### ISSUE TITLE
test:first job: script should be a string or an array of a strings

### ISSUE THREAD

**Issue by d33tah** [gitlabhq/gitlab-ci#635]
Consider this file:

```
image: debian:sid

test:first:
  script:
  - true
```

Gitlab CI evaluated "true" as a boolean instead of a command, which in itself is worrying. Why isn't it treating this as a string that should be ran? Perhaps there's a security vulnerability there?

**Comment by ayufan** [comment]
@d33tah 

Nope, this is how YAML parser works. The true is of boolean type and gitlab-ci.yml parser is strict about it.
