### ISSUE TITLE
Is it possible build only on tag push event?

### ISSUE THREAD

**Issue by thepianist2** [gitlabhq/gitlab-ci#637]
Is it possible build only on tag push event?

I have seen web hooks but does not help me , because I 'm going to use to copy the files to a CDN .

It is possible? and how? tnx

**Comment by ayufan** [comment]
Add to `gitlab-ci.yml` the `only` directive:
```
myjob:
  script: test
  only:
  - master
```

**Comment by thepianist2** [comment]
Yes, thanks,  but the problem is I want to do it only when the push is made tags,

as in this picture , but in the build

![hook](https://cloud.githubusercontent.com/assets/2571223/12233190/5d368474-b865-11e5-9137-aa7bb0141a68.png)

**Comment by ayufan** [comment]
Not sure what you mean, can you be more clear?

**Comment by thepianist2** [comment]
it 's worth, when I have a project with continuous integration gitlab at the time of making the push automatically tasks that are within the gitlab - ci.yml file are released , what I do is that only in time to make the push of a tag ( git push --follow -tags ) , the tasks of file ci.ym gitlab - run , is this possible?

I hope I explained better.

Thank you

**Comment by ayufan** [comment]
Great. Try to add to `.gitlab-ci.yml` `tags`:

```
myjob:
  script: test
  only:
  - tags
```

**Comment by thepianist2** [comment]
Thank you very much , worked properly .

Solved.
