### ISSUE TITLE
Incorrect document about using mysql service with empty password

### ISSUE THREAD

**Issue by oanhnn** [gitlabhq/gitlab-ci#649]
I try validate gitlab ci script follow [document](https://github.com/gitlabhq/gitlab-ci/blob/master/doc/docker/using_docker_images.md#configuring-services) but it is invalid
![Validate Gitlab CI script][screenshot]
Can you help me correct config mysql service with empty password?

[screenshot]: https://www.evernote.com/shard/s716/sh/9c318cfd-3917-4645-95cf-bb2a1465a5b2/6f2a4c7b12164daaf82d1ad10671a1e3/res/7fa7af9d-37e9-4663-939d-e4c8addec1cb/lint.jpg "Validate Gitlab CI script"

**Comment by grzesiek** [comment]
@oanhnn try `MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

**Comment by oanhnn** [comment]
Thank you! Please update to document.
