### ISSUE TITLE
Only master && only pull request, no CI on push master->master

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [gitlabhq/gitlab-ci#655]
I have xcode project where I am creating gitlab CI pipeline to run tests on every push and to run build for xcode only master.
One of the steps in Build is to increment build number in xcode info.plist number(I want to automate build number increment, since the build itself is automated). Once build is done I would like to keep the changes to my info.plist file(build number), otherwise automation of incrementing this number doesn't make sense.

So my CI final job would be to git commit and git push master -> master. I assume this would trigger my pipeline once again and so the infinite loop starts? 
Is there a way to not trigger the CI pipeline if push/commit/merge is done from the Runner or at least have my pipeline run only when it is it is a merge/pull request to master and not push from master to master? 

I haven't found a way to do so, so I am summiting this issue.

**Comment by bershan2** [comment]
1. This is a mirror repository, it litteraly [says](https://gitlab.com/gitlab-org/gitlab-ce) "Mirror of GitLab CI, please use GitLab.com repo for issues <https://gitlab.com/gitlab-org/gitlab-ce>".
2. This repository has been inactive for [over a year!](https://github.com/gitlabhq/gitlab-ci/graphs/contributors)
