### ISSUE TITLE
Build fails bre-build

### ISSUE THREAD

**Issue by elemakil** [gitlabhq/gitlab-ci#96]
Hi,

I've setup gitlab_ci as per the official guide, locally cloned my repository to /home/gitlab_ci/ci-projects and added the deploy keys to gitlab.
However then testing the setup building immediately fails in the "pre-build" stage (I guess). The log shows:  

> cd /home/gitlab_ci/ci-projects/krams.git && git fetch && git reset --hard && git checkout 95825a67aeaaa1fa5650a49164678a2e0b00ba77
> fatal: '/home/git/repositories/krams.git' does not appear to be a git repository
> fatal: The remote end hung up unexpectedly

/home/git/repositories/ is the local repository path, krams the repository name. I have no idea why this fails... the first three commands finish without any problems and the user (gitlab_ci) has full read/write access to the directory. I tried manually pushing a modification to git (just to check whether this works, I assume that gitlab_ci won't do this), which fails with this obscure error message:  

> gitlab_ci@divzero:~/ci-projects/krams.git$ git push
> Counting objects: 3, done.
> Delta compression using up to 16 threads.
> Compressing objects: 100% (2/2), done.
> Writing objects: 100% (2/2), 260 bytes, done.
> Total 2 (delta 1), reused 0 (delta 0)
> Unpacking objects: 100% (2/2), done.
> remote: Empty compile time value given to use lib at hooks/update line 10
> remote: Use of uninitialized value in require at hooks/update line 11.
> remote: Can't locate Gitolite/Hooks/Update.pm in @INC (@INC contains:  /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at hooks/update line 11.
> remote: BEGIN failed--compilation aborted at hooks/update line 11.
> remote: error: hook declined to update refs/heads/master To /home/git/repositories/krams.git
>  ! [remote rejected] master -> master (hook declined)
> error: failed to push some refs to '/home/git/repositories/krams.git'  

Any suggestions / help?

**Comment by jvanbaarsen** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
